import { equal, textParts } from "yuke:internal/test";
import { ChatView } from "yuke:internal/chat-view";
import { root } from "yuke:internal/core";
import { plugins } from "yuke:internal/ext";
import { tuiPlugin } from "yuke:internal/tui";
import { chatPlugin } from "yuke:internal/chat";
plugins.use(tuiPlugin); const off = plugins.use(chatPlugin);
const view = new ChatView({ partsOf: textParts(() => "history") });
root.setActive(view); root.flush();
const welcome = view.presentationViews.some(child => child.text === "new chat");
view.transcript.setOutline([{ id: 1, type: "user" }], null);
root.invalidate(); root.flush();
const history = view.presentationViews.length === 0 && view.transcript.pager.rect() !== null;
root.setActive(null); off.dispose();
equal(welcome && history ? "ok" : [welcome, history].join(","), "ok");
