import { equal } from "yuke:internal/test";
import { ChatSurface, Session } from "yuke:internal/chat";
import { ChatView } from "yuke:internal/chat-view";
import { events } from "yuke:internal/kernel";
import { column, child, fixed } from "yuke:internal/layout";
import { Context, Scope } from "yuke:internal/ext";
const view = new ChatView(new Session()), scope = new Scope("bad");
let errors = 0, disposed = 0;
const off = events.on("ext.failed", () => errors++);
const surface = new ChatSurface(new Context(scope, "bad"), null);
const remove = surface.presentation((_chat, owner) => {
  owner.effect(() => () => disposed++);
  return () => column([child("composer", fixed(1)), child("composer", fixed(1))]);
});
view.layout({ x: 0, y: 0, w: 30, h: 10 });
const duplicate = errors === 1 && disposed === 1 && view.presentation === null && view.composer.rect.w === 30;
remove();
surface.presentation((_chat, owner) => { owner.effect(() => () => disposed++); throw new Error("factory failure"); });
view.layout({ x: 0, y: 0, w: 30, h: 10 });
scope.dispose(); off();
equal(duplicate && errors === 2 && disposed === 2 ? "ok" : [duplicate, errors, disposed].join(","), "ok");
