// Generated by tools/sqlgen. DO NOT EDIT.
const sql = @import("sql");

pub const InsertConfig = sql.ExecQuery(
    \\INSERT INTO session_configs(session_id, config_rev, model, reasoning)
    \\    VALUES (:session_id, :config_rev, :model, :reasoning);
,
    struct {
        session_id: [16]u8,
        config_rev: u64,
        model: []const u8,
        reasoning: []const u8,
    },
);

pub const AdvanceConfig = sql.OneQuery(
    \\UPDATE sessions SET
    \\    model           = :model,
    \\    reasoning       = :reasoning,
    \\    config_rev      = :config_rev,
    \\    config_rev_high = MAX(config_rev_high, :config_rev),
    \\    projection_seq  = :seq,
    \\    updated_at_ms   = MAX(updated_at_ms, :updated_at_ms)
    \\WHERE id = :id AND :config_rev >= config_rev_high RETURNING 1 AS advanced;
,
    struct {
        model: []const u8,
        reasoning: []const u8,
        config_rev: u64,
        seq: u64,
        updated_at_ms: u64,
        id: [16]u8,
    },
    struct {
        advanced: i64,
    },
);

pub const ConfigByRevision = sql.OptionalQuery(
    \\SELECT model, reasoning FROM session_configs WHERE session_id = :session_id AND config_rev = :config_rev;
,
    struct {
        session_id: [16]u8,
        config_rev: u64,
    },
    struct {
        model: []const u8,
        reasoning: []const u8,
    },
);

pub const AllocSeq = sql.OneQuery(
    \\UPDATE sessions SET seq_high = seq_high + 1 WHERE id = :id RETURNING seq_high;
,
    struct {
        id: [16]u8,
    },
    struct {
        seq_high: u64,
    },
);

pub const AppendEvent = sql.ExecQuery(
    \\INSERT INTO events(session_id, seq, event_id, committed_at_ms, name, payload)
    \\    VALUES (:session_id, :seq, :event_id, :committed_at_ms, :name, :payload);
,
    struct {
        session_id: [16]u8,
        seq: u64,
        event_id: [16]u8,
        committed_at_ms: u64,
        name: []const u8,
        payload: []const u8,
    },
);

pub const ReadHigh = sql.OptionalQuery(
    \\SELECT seq_high, message_id_high, run_id_high, input_id_high, config_rev_high, message_count
    \\    FROM sessions WHERE id = :id;
,
    struct {
        id: [16]u8,
    },
    struct {
        seq_high: u64,
        message_id_high: u64,
        run_id_high: u64,
        input_id_high: u64,
        config_rev_high: u64,
        message_count: u64,
    },
);

pub const AllocRunId = sql.OneQuery(
    \\UPDATE sessions SET run_id_high = run_id_high + 1 WHERE id = :id RETURNING run_id_high;
,
    struct {
        id: [16]u8,
    },
    struct {
        run_id_high: u64,
    },
);

pub const AllocMessageId = sql.OneQuery(
    \\UPDATE sessions SET message_id_high = message_id_high + 1 WHERE id = :id RETURNING message_id_high;
,
    struct {
        id: [16]u8,
    },
    struct {
        message_id_high: u64,
    },
);

pub const AllocInputId = sql.OneQuery(
    \\UPDATE sessions SET input_id_high = input_id_high + 1 WHERE id = :id RETURNING input_id_high;
,
    struct {
        id: [16]u8,
    },
    struct {
        input_id_high: u64,
    },
);

pub const LatestTurnDone = sql.OptionalQuery(
    \\SELECT payload FROM events WHERE session_id = :session_id AND name = 'run.done'
    \\    AND json_extract(payload, '$.kind') = 'turn' ORDER BY seq DESC LIMIT 1;
,
    struct {
        session_id: [16]u8,
    },
    struct {
        payload: []const u8,
    },
);

pub const InsertPendingInput = sql.ExecQuery(
    \\INSERT INTO pending_inputs(session_id, input_id, seq, queued_at_ms, payload)
    \\    VALUES (:session_id, :input_id, :seq, :queued_at_ms, :payload);
,
    struct {
        session_id: [16]u8,
        input_id: u64,
        seq: u64,
        queued_at_ms: u64,
        payload: []const u8,
    },
);

pub const PendingInputById = sql.OptionalQuery(
    \\SELECT p.input_id AS row_input_id,
    \\       p.seq,
    \\       p.queued_at_ms,
    \\       p.payload,
    \\       e.name AS event_name
    \\FROM pending_inputs p
    \\JOIN events e ON e.session_id = p.session_id AND e.seq = p.seq
    \\WHERE p.session_id = :session_id AND p.input_id = :input_id;
,
    struct {
        session_id: [16]u8,
        input_id: u64,
    },
    struct {
        row_input_id: u64,
        seq: u64,
        queued_at_ms: u64,
        payload: []const u8,
        event_name: []const u8,
    },
);

pub const PendingInputs = sql.ManyQuery(
    \\SELECT p.input_id AS row_input_id,
    \\       p.seq,
    \\       p.queued_at_ms,
    \\       p.payload,
    \\       e.name AS event_name
    \\FROM pending_inputs p
    \\JOIN events e ON e.session_id = p.session_id AND e.seq = p.seq
    \\WHERE p.session_id = :session_id
    \\ORDER BY p.seq ASC;
,
    struct {
        session_id: [16]u8,
    },
    struct {
        row_input_id: u64,
        seq: u64,
        queued_at_ms: u64,
        payload: []const u8,
        event_name: []const u8,
    },
);

pub const PendingInputCount = sql.OneQuery(
    \\SELECT count(*) AS depth
    \\FROM pending_inputs
    \\WHERE session_id = :session_id;
,
    struct {
        session_id: [16]u8,
    },
    struct {
        depth: i64,
    },
);

pub const DeletePendingInput = sql.OneQuery(
    \\DELETE FROM pending_inputs
    \\WHERE session_id = :session_id AND input_id = :input_id
    \\RETURNING 1 AS deleted;
,
    struct {
        session_id: [16]u8,
        input_id: u64,
    },
    struct {
        deleted: i64,
    },
);

pub const ChildReportCredits = sql.OneQuery(
    \\WITH RECURSIVE tree(id) AS (
    \\    SELECT id FROM sessions WHERE parent_id = :parent_id
    \\    UNION
    \\    SELECT s.id FROM sessions s JOIN tree t ON s.parent_id = t.id
    \\)
    \\SELECT
    \\    (SELECT count(*) FROM pending_inputs p JOIN tree t ON t.id = p.session_id) +
    \\    (SELECT count(*) FROM sessions s JOIN tree t ON t.id = s.id WHERE s.open_run_kind = 'turn') +
    \\    (SELECT count(*) FROM pending_inputs WHERE session_id = :parent_id AND json_extract(payload, '$.source.type') IN ('child_report', 'child_input_canceled')) AS used;
,
    struct {
        parent_id: [16]u8,
    },
    struct {
        used: i64,
    },
);

pub const ProtectedInputCount = sql.OneQuery(
    \\SELECT count(*) AS depth FROM pending_inputs
    \\WHERE session_id = :session_id AND coalesce(json_extract(payload, '$.source.type'), 'parent_instruction') <> 'parent_instruction';
,
    struct {
        session_id: [16]u8,
    },
    struct {
        depth: i64,
    },
);

pub const InsertMessage = sql.ExecQuery(
    \\INSERT INTO messages(
    \\    session_id, message_id, seq, role, run_id, config_rev, model, protocol, finish,
    \\    tokens_input, tokens_output, tokens_reasoning, tokens_cache_read, tokens_cache_write, cost, created_at_ms
    \\) VALUES (
    \\    :session_id, :message_id, :seq, :role, :run_id, :config_rev, :model, :protocol, :finish,
    \\    :tokens_input, :tokens_output, :tokens_reasoning, :tokens_cache_read, :tokens_cache_write, :cost, :created_at_ms
    \\);
,
    struct {
        session_id: [16]u8,
        message_id: u64,
        seq: u64,
        role: []const u8,
        run_id: ?u64,
        config_rev: ?u64,
        model: ?[]const u8,
        protocol: ?[]const u8,
        finish: ?[]const u8,
        tokens_input: ?u64,
        tokens_output: ?u64,
        tokens_reasoning: ?u64,
        tokens_cache_read: ?u64,
        tokens_cache_write: ?u64,
        cost: ?f64,
        created_at_ms: u64,
    },
);

pub const AdvanceMessage = sql.OneQuery(
    \\UPDATE sessions SET
    \\    message_count           = message_count + 1,
    \\    message_id_high         = MAX(message_id_high, :message_id),
    \\    usage_input_total       = usage_input_total       + :add_input,
    \\    usage_output_total      = usage_output_total      + :add_output,
    \\    usage_reasoning_total   = usage_reasoning_total    + :add_reasoning,
    \\    usage_cache_read_total  = usage_cache_read_total   + :add_cache_read,
    \\    usage_cache_write_total = usage_cache_write_total  + :add_cache_write,
    \\    projection_seq          = :seq,
    \\    updated_at_ms           = MAX(updated_at_ms, :updated_at_ms)
    \\WHERE id = :id RETURNING 1 AS advanced;
,
    struct {
        message_id: u64,
        add_input: u64,
        add_output: u64,
        add_reasoning: u64,
        add_cache_read: u64,
        add_cache_write: u64,
        seq: u64,
        updated_at_ms: u64,
        id: [16]u8,
    },
    struct {
        advanced: i64,
    },
);

pub const MessagePage = sql.ManyQuery(
    \\SELECT m.message_id AS message_id, e.payload AS payload
    \\FROM messages m JOIN events e ON e.session_id = m.session_id AND e.seq = m.seq
    \\WHERE m.session_id = :session_id AND m.message_id < :cursor_message_id
    \\ORDER BY m.message_id DESC
    \\LIMIT :limit;
,
    struct {
        session_id: [16]u8,
        cursor_message_id: u64,
        limit: i64,
    },
    struct {
        message_id: u64,
        payload: []const u8,
    },
);

pub const MessageTail = sql.ManyQuery(
    \\SELECT t.message_id AS message_id, e.payload AS payload
    \\FROM (
    \\    SELECT session_id, message_id, seq FROM messages
    \\    WHERE session_id = :session_id
    \\    ORDER BY message_id DESC
    \\    LIMIT :limit
    \\) t JOIN events e ON e.session_id = t.session_id AND e.seq = t.seq
    \\ORDER BY t.message_id ASC;
,
    struct {
        session_id: [16]u8,
        limit: i64,
    },
    struct {
        message_id: u64,
        payload: []const u8,
    },
);

pub const LastAssistantUsage = sql.OptionalQuery(
    \\SELECT tokens_input, tokens_output, tokens_reasoning, tokens_cache_read, tokens_cache_write
    \\FROM messages
    \\WHERE session_id = :session_id AND role = 'assistant' AND tokens_input IS NOT NULL
    \\ORDER BY message_id DESC
    \\LIMIT 1;
,
    struct {
        session_id: [16]u8,
    },
    struct {
        tokens_input: ?u64,
        tokens_output: ?u64,
        tokens_reasoning: ?u64,
        tokens_cache_read: ?u64,
        tokens_cache_write: ?u64,
    },
);

pub const RunReportMessages = sql.ManyQuery(
    \\SELECT e.payload FROM messages m JOIN events e ON e.session_id = m.session_id AND e.seq = m.seq
    \\WHERE m.session_id = :session_id AND m.run_id = :run_id AND m.role = 'assistant'
    \\ORDER BY m.message_id DESC;
,
    struct {
        session_id: [16]u8,
        run_id: u64,
    },
    struct {
        payload: []const u8,
    },
);

pub const InsertSession = sql.ExecQuery(
    \\INSERT INTO sessions(
    \\    id, root, origin, parent_id, parent_message_id, parent_part_id, source_id,
    \\    profile, model, reasoning, config_rev, max_rounds, title, agent, name,
    \\    created_by_name, created_by_version, created_at_ms, updated_at_ms
    \\) VALUES (
    \\    :id, :root, :origin, :parent_id, :parent_message_id, :parent_part_id, :source_id,
    \\    :profile, :model, :reasoning, :config_rev, :max_rounds, :title, :agent, :name,
    \\    :created_by_name, :created_by_version, :created_at_ms, :updated_at_ms
    \\);
,
    struct {
        id: [16]u8,
        root: []const u8,
        origin: []const u8,
        parent_id: ?[16]u8,
        parent_message_id: ?u64,
        parent_part_id: ?u64,
        source_id: ?[16]u8,
        profile: []const u8,
        model: []const u8,
        reasoning: []const u8,
        config_rev: u64,
        max_rounds: ?u64,
        title: []const u8,
        agent: ?[]const u8,
        name: ?[]const u8,
        created_by_name: ?[]const u8,
        created_by_version: ?[]const u8,
        created_at_ms: u64,
        updated_at_ms: u64,
    },
);

pub const SessionExists = sql.OptionalQuery(
    \\SELECT 1 AS present FROM sessions WHERE id = :id;
,
    struct {
        id: [16]u8,
    },
    struct {
        present: i64,
    },
);

pub const SessionSnapshot = sql.OptionalQuery(
    \\SELECT
    \\    id, root,
    \\    origin, parent_id, parent_message_id, parent_part_id, source_id,
    \\    profile, model, reasoning, config_rev, max_rounds, title, agent, name,
    \\    created_by_name, created_by_version,
    \\    message_count,
    \\    usage_input_total, usage_output_total, usage_reasoning_total, usage_cache_read_total, usage_cache_write_total,
    \\    created_at_ms, updated_at_ms,
    \\    open_run_id, open_run_kind, open_run_started_at_ms,
    \\    ctx_tokens_input, ctx_tokens_output, ctx_tokens_reasoning, ctx_tokens_cache_read, ctx_tokens_cache_write
    \\FROM session_context
    \\WHERE id = :id;
,
    struct {
        id: [16]u8,
    },
    struct {
        id: [16]u8,
        root: []const u8,
        origin: []const u8,
        parent_id: ?[16]u8,
        parent_message_id: ?u64,
        parent_part_id: ?u64,
        source_id: ?[16]u8,
        profile: []const u8,
        model: []const u8,
        reasoning: []const u8,
        config_rev: u64,
        max_rounds: ?u64,
        title: []const u8,
        agent: ?[]const u8,
        name: ?[]const u8,
        created_by_name: ?[]const u8,
        created_by_version: ?[]const u8,
        message_count: u64,
        usage_input_total: u64,
        usage_output_total: u64,
        usage_reasoning_total: u64,
        usage_cache_read_total: u64,
        usage_cache_write_total: u64,
        created_at_ms: u64,
        updated_at_ms: u64,
        open_run_id: ?u64,
        open_run_kind: ?[]const u8,
        open_run_started_at_ms: ?u64,
        ctx_tokens_input: ?u64,
        ctx_tokens_output: ?u64,
        ctx_tokens_reasoning: ?u64,
        ctx_tokens_cache_read: ?u64,
        ctx_tokens_cache_write: ?u64,
    },
);

pub const SetOpenRun = sql.OneQuery(
    \\UPDATE sessions SET
    \\    open_run_id = :run_id,
    \\    open_run_kind = :kind,
    \\    open_run_started_at_ms = :started_at_ms
    \\WHERE id = :id AND open_run_id IS NULL
    \\RETURNING 1 AS changed;
,
    struct {
        run_id: u64,
        kind: []const u8,
        started_at_ms: u64,
        id: [16]u8,
    },
    struct {
        changed: i64,
    },
);

pub const ClearOpenRun = sql.OneQuery(
    \\UPDATE sessions SET
    \\    open_run_id = NULL,
    \\    open_run_kind = NULL,
    \\    open_run_started_at_ms = NULL
    \\WHERE id = :id
    \\  AND open_run_id = :run_id
    \\  AND open_run_kind = :kind
    \\  AND open_run_started_at_ms = :started_at_ms
    \\RETURNING 1 AS changed;
,
    struct {
        id: [16]u8,
        run_id: u64,
        kind: []const u8,
        started_at_ms: u64,
    },
    struct {
        changed: i64,
    },
);

pub const SessionPageRecent = sql.ManyQuery(
    \\SELECT
    \\    id, root,
    \\    origin, parent_id, parent_message_id, parent_part_id, source_id,
    \\    profile, model, reasoning, config_rev, max_rounds, title, agent, name,
    \\    created_by_name, created_by_version,
    \\    message_count,
    \\    usage_input_total, usage_output_total, usage_reasoning_total, usage_cache_read_total, usage_cache_write_total,
    \\    created_at_ms, updated_at_ms,
    \\    ctx_tokens_input, ctx_tokens_output, ctx_tokens_reasoning, ctx_tokens_cache_read, ctx_tokens_cache_write
    \\FROM session_context
    \\WHERE (NOT :top_level OR origin IN ('root', 'fork'))
    \\  AND (updated_at_ms, id) < (:cursor_updated_at_ms, :cursor_id)
    \\ORDER BY updated_at_ms DESC, id DESC
    \\LIMIT :limit;
,
    struct {
        top_level: bool,
        cursor_updated_at_ms: u64,
        cursor_id: [16]u8,
        limit: i64,
    },
    struct {
        id: [16]u8,
        root: []const u8,
        origin: []const u8,
        parent_id: ?[16]u8,
        parent_message_id: ?u64,
        parent_part_id: ?u64,
        source_id: ?[16]u8,
        profile: []const u8,
        model: []const u8,
        reasoning: []const u8,
        config_rev: u64,
        max_rounds: ?u64,
        title: []const u8,
        agent: ?[]const u8,
        name: ?[]const u8,
        created_by_name: ?[]const u8,
        created_by_version: ?[]const u8,
        message_count: u64,
        usage_input_total: u64,
        usage_output_total: u64,
        usage_reasoning_total: u64,
        usage_cache_read_total: u64,
        usage_cache_write_total: u64,
        created_at_ms: u64,
        updated_at_ms: u64,
        ctx_tokens_input: ?u64,
        ctx_tokens_output: ?u64,
        ctx_tokens_reasoning: ?u64,
        ctx_tokens_cache_read: ?u64,
        ctx_tokens_cache_write: ?u64,
    },
);

pub const SessionPageParent = sql.ManyQuery(
    \\SELECT
    \\    id, root,
    \\    origin, parent_id, parent_message_id, parent_part_id, source_id,
    \\    profile, model, reasoning, config_rev, max_rounds, title, agent, name,
    \\    created_by_name, created_by_version,
    \\    message_count,
    \\    usage_input_total, usage_output_total, usage_reasoning_total, usage_cache_read_total, usage_cache_write_total,
    \\    created_at_ms, updated_at_ms,
    \\    ctx_tokens_input, ctx_tokens_output, ctx_tokens_reasoning, ctx_tokens_cache_read, ctx_tokens_cache_write
    \\FROM session_context
    \\WHERE parent_id = :filter_parent_id
    \\  AND (NOT :top_level OR origin IN ('root', 'fork'))
    \\  AND (updated_at_ms, id) < (:cursor_updated_at_ms, :cursor_id)
    \\ORDER BY updated_at_ms DESC, id DESC
    \\LIMIT :limit;
,
    struct {
        filter_parent_id: [16]u8,
        top_level: bool,
        cursor_updated_at_ms: u64,
        cursor_id: [16]u8,
        limit: i64,
    },
    struct {
        id: [16]u8,
        root: []const u8,
        origin: []const u8,
        parent_id: ?[16]u8,
        parent_message_id: ?u64,
        parent_part_id: ?u64,
        source_id: ?[16]u8,
        profile: []const u8,
        model: []const u8,
        reasoning: []const u8,
        config_rev: u64,
        max_rounds: ?u64,
        title: []const u8,
        agent: ?[]const u8,
        name: ?[]const u8,
        created_by_name: ?[]const u8,
        created_by_version: ?[]const u8,
        message_count: u64,
        usage_input_total: u64,
        usage_output_total: u64,
        usage_reasoning_total: u64,
        usage_cache_read_total: u64,
        usage_cache_write_total: u64,
        created_at_ms: u64,
        updated_at_ms: u64,
        ctx_tokens_input: ?u64,
        ctx_tokens_output: ?u64,
        ctx_tokens_reasoning: ?u64,
        ctx_tokens_cache_read: ?u64,
        ctx_tokens_cache_write: ?u64,
    },
);

pub const SessionCountRecent = sql.OneQuery(
    \\SELECT count(*) AS total FROM sessions
    \\WHERE (NOT :top_level OR origin IN ('root', 'fork'));
,
    struct {
        top_level: bool,
    },
    struct {
        total: u64,
    },
);

pub const SessionCountParent = sql.OneQuery(
    \\SELECT count(*) AS total FROM sessions
    \\WHERE parent_id = :filter_parent_id
    \\  AND (NOT :top_level OR origin IN ('root', 'fork'));
,
    struct {
        filter_parent_id: [16]u8,
        top_level: bool,
    },
    struct {
        total: u64,
    },
);

pub const InsertPrompt = sql.ExecQuery(
    \\INSERT INTO session_prompts(session_id, prompt, base_prompt) VALUES (:session_id, :prompt, :base_prompt);
,
    struct {
        session_id: [16]u8,
        prompt: []const u8,
        base_prompt: ?[]const u8,
    },
);

pub const SelectPrompt = sql.OptionalQuery(
    \\SELECT prompt FROM session_prompts WHERE session_id = :session_id;
,
    struct {
        session_id: [16]u8,
    },
    struct {
        prompt: []const u8,
    },
);

pub const SelectBasePrompt = sql.OptionalQuery(
    \\SELECT base_prompt FROM session_prompts WHERE session_id = :session_id;
,
    struct {
        session_id: [16]u8,
    },
    struct {
        base_prompt: ?[]const u8,
    },
);

pub const DeleteSession = sql.ExecQuery(
    \\DELETE FROM sessions WHERE id = :id;
,
    struct {
        id: [16]u8,
    },
);

pub const SessionChildIds = sql.ManyQuery(
    \\SELECT id FROM sessions WHERE parent_id = :parent_id ORDER BY id;
,
    struct {
        parent_id: [16]u8,
    },
    struct {
        id: [16]u8,
    },
);

pub const SessionRecoveryCandidates = sql.ManyQuery(
    \\SELECT id FROM sessions
    \\WHERE root = :root
    \\  AND (open_run_id IS NOT NULL OR EXISTS (SELECT 1 FROM pending_inputs WHERE session_id = sessions.id))
    \\ORDER BY created_at_ms, id;
,
    struct {
        root: []const u8,
    },
    struct {
        id: [16]u8,
    },
);

pub const ChildAdmissionCandidates = sql.ManyQuery(
    \\WITH RECURSIVE tree(id) AS (
    \\    SELECT id FROM sessions WHERE parent_id = :parent_id
    \\    UNION
    \\    SELECT s.id FROM sessions s JOIN tree t ON s.parent_id = t.id
    \\)
    \\SELECT s.id FROM sessions s
    \\    JOIN tree t ON t.id = s.id
    \\    JOIN pending_inputs p ON p.session_id = s.id
    \\    JOIN events e ON e.session_id = p.session_id AND e.seq = p.seq
    \\GROUP BY s.id ORDER BY min(e.rowid);
,
    struct {
        parent_id: [16]u8,
    },
    struct {
        id: [16]u8,
    },
);

pub const ChildByName = sql.OptionalQuery(
    \\SELECT id FROM sessions WHERE parent_id = :parent_id AND name = :name;
,
    struct {
        parent_id: [16]u8,
        name: []const u8,
    },
    struct {
        id: [16]u8,
    },
);

pub const Queries = struct {
    insert_config: InsertConfig,
    advance_config: AdvanceConfig,
    config_by_revision: ConfigByRevision,
    alloc_seq: AllocSeq,
    append_event: AppendEvent,
    read_high: ReadHigh,
    alloc_run_id: AllocRunId,
    alloc_message_id: AllocMessageId,
    alloc_input_id: AllocInputId,
    latest_turn_done: LatestTurnDone,
    insert_pending_input: InsertPendingInput,
    pending_input_by_id: PendingInputById,
    pending_inputs: PendingInputs,
    pending_input_count: PendingInputCount,
    delete_pending_input: DeletePendingInput,
    child_report_credits: ChildReportCredits,
    protected_input_count: ProtectedInputCount,
    insert_message: InsertMessage,
    advance_message: AdvanceMessage,
    message_page: MessagePage,
    message_tail: MessageTail,
    last_assistant_usage: LastAssistantUsage,
    run_report_messages: RunReportMessages,
    insert_session: InsertSession,
    session_exists: SessionExists,
    session_snapshot: SessionSnapshot,
    set_open_run: SetOpenRun,
    clear_open_run: ClearOpenRun,
    session_page_recent: SessionPageRecent,
    session_page_parent: SessionPageParent,
    session_count_recent: SessionCountRecent,
    session_count_parent: SessionCountParent,
    insert_prompt: InsertPrompt,
    select_prompt: SelectPrompt,
    select_base_prompt: SelectBasePrompt,
    delete_session: DeleteSession,
    session_child_ids: SessionChildIds,
    session_recovery_candidates: SessionRecoveryCandidates,
    child_admission_candidates: ChildAdmissionCandidates,
    child_by_name: ChildByName,

    pub fn prepareAll(conn: sql.Connection) !@This() {
        return sql.prepareAll(@This(), conn);
    }

    pub fn deinit(self: *@This()) void {
        sql.deinitAll(self);
    }
};
