import { check } from "yuke:internal/test";
import { Document } from "yuke:internal/md";
const doc = new Document();
let source = "# Prefix\n\nstable 世界 é 👩‍💻\n\n```txt\nbody\n```\n\nTail";
doc.setText(source);
doc.rows(24);
const heldRows = doc.rows(24);
const heldJson = JSON.stringify(heldRows);
const prefix = doc.cache.get(0);
const codeAt = source.indexOf("```txt");
const code = doc.cache.get(codeAt);
check("closed-caches-exist", !!prefix && !!code);
for (const delta of [" extended", "\r", "\n\r\nNext", "\n===", "\n\n| a | b |\n|---|---|\n| 1 | 2 |", "\n\nEnd"]) {
  source += delta;
  doc.setText(source);
  const fresh = new Document();
  fresh.setText(source);
  check("snapshot", JSON.stringify(heldRows) === heldJson);
  check("append-rows", JSON.stringify(doc.rows(24)) === JSON.stringify(fresh.rows(24)));
  check("append-blocks", JSON.stringify(doc.blocks()) === JSON.stringify(fresh.blocks()));
  check("prefix-cache", doc.cache.get(0) === prefix);
  check("closed-tail-cache", doc.cache.get(codeAt) === code);
  const closed = new Set(doc.parsed.filter(block => !block.open).map(block => block.at));
  check("no-orphan-cache", [...doc.cache.keys()].every(at => closed.has(at)));
}
const fresh = new Document();
fresh.setText(source);
check("resize", JSON.stringify(doc.rows(9)) === JSON.stringify(fresh.rows(9)));
check("replacement-changed", doc.setText("replacement\r\ntext"));
check("replacement-releases-cache", doc.cache.size === 0);
check("replacement-normalized", doc.sourceText() === "replacement\ntext");
check("unchanged", !doc.setText("replacement\r\ntext"));
check("empty", doc.setText("") && doc.rows(24).length === 0 && doc.cache.size === 0);
const short = new Document();
short.setText("```txt\nlarge closed block\n```\n\nTail");
short.rows(24);
const shortCode = short.cache.get(0);
short.setText(short.sourceText() + " extended");
short.rows(24);
check("two-block-cache", !!shortCode && short.cache.get(0) === shortCode);
