package tests

import _ "src:auth"
import _ "src:client"
import _ "src:daemon"
import _ "src:daemon/store"
import _ "src:daemon/store/queries"
import _ "src:js"
import _ "src:paths"
import _ "src:provider"
import _ "src:relay"
import _ "src:secret"
import _ "src:term"
import _ "src:term/ui"
import _ "src:tui"
import _ "src:wire"

import _ "libs:bindings/curl"
import _ "libs:bindings/quickjs"
import _ "libs:bindings/sqlite"
import _ "libs:http"
import _ "libs:http/server"
import _ "libs:http/sse"
import _ "libs:offload"
import _ "libs:testsupport"
import _ "libs:websocket"
