CREATE TABLE IF NOT EXISTS catalog_meta (k TEXT PRIMARY KEY, v TEXT NOT NULL) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS catalog_providers (id TEXT PRIMARY KEY, data TEXT NOT NULL) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS catalog_models (id TEXT PRIMARY KEY, provider_id TEXT NOT NULL, data TEXT NOT NULL) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS catalog_models_by_provider ON catalog_models (provider_id);
