// Code generated by tools/sqlgen from src/daemon/store/migrations and
// src/daemon/store/queries. DO NOT EDIT.
// Regenerate with ./build.py sql.

package queries

import "src:wire"

import "libs:bindings/sqlite"

Create_Session_Params :: struct {
    id:                     wire.Session_Id,
    workspace_id:           wire.Workspace_Id,
    origin:                 string,
    parent_id:              Maybe(wire.Session_Id),
    parent_message_id:      Maybe(wire.Message_Id),
    parent_part_id:         Maybe(wire.Part_Id),
    source_id:              Maybe(wire.Session_Id),
    job_id:                 Maybe(wire.Job_Id),
    profile:                string,
    model:                  string,
    reasoning:              string,
    config_rev:             wire.Config_Rev,
    permission:             string,
    max_rounds:             Maybe(u64),
    title:                  string,
    agent:                  Maybe(string),
    created_by_name:        Maybe(string),
    created_by_version:     Maybe(string),
    created_at_ms:          u64,
    updated_at_ms:          u64,
    open_run_id:            Maybe(wire.Run_Id),
    open_run_kind:          Maybe(string),
    open_run_started_at_ms: Maybe(u64),
}

Session_Row :: struct {
    id:                     wire.Session_Id,
    workspace_id:           wire.Workspace_Id,
    origin:                 string,
    parent_id:              Maybe(wire.Session_Id),
    parent_message_id:      Maybe(wire.Message_Id),
    parent_part_id:         Maybe(wire.Part_Id),
    source_id:              Maybe(wire.Session_Id),
    job_id:                 Maybe(wire.Job_Id),
    profile:                string,
    model:                  string,
    reasoning:              string,
    config_rev:             wire.Config_Rev,
    permission:             string,
    max_rounds:             Maybe(u64),
    title:                  string,
    agent:                  Maybe(string),
    created_by_name:        Maybe(string),
    created_by_version:     Maybe(string),
    message_count:          u64,
    created_at_ms:          u64,
    updated_at_ms:          u64,
    open_run_id:            Maybe(wire.Run_Id),
    open_run_kind:          Maybe(string),
    open_run_started_at_ms: Maybe(u64),
}

Insert_Message_Params :: struct {
    session_id:         wire.Session_Id,
    message_id:         wire.Message_Id,
    seq:                wire.Seq,
    role:               string,
    run_id:             Maybe(wire.Run_Id),
    config_rev:         Maybe(wire.Config_Rev),
    model:              Maybe(string),
    protocol:           Maybe(string),
    finish:             Maybe(string),
    tokens_input:       Maybe(u64),
    tokens_output:      Maybe(u64),
    tokens_reasoning:   Maybe(u64),
    tokens_cache_read:  Maybe(u64),
    tokens_cache_write: Maybe(u64),
    cost:               Maybe(f64),
    created_at_ms:      u64,
}

Insert_Config_Params :: struct {
    session_id: wire.Session_Id,
    config_rev: wire.Config_Rev,
    model:      string,
    reasoning:  string,
}

Catalog_Size_Row :: struct {
    providers: u64,
    models:    u64,
}

Session_Prompt_Row :: struct {
    prompt: string,
}

Session_Config_Row :: struct {
    config_rev: wire.Config_Rev,
    model:      string,
    reasoning:  string,
}

Read_High_Row :: struct {
    seq_high:        wire.Seq,
    message_id_high: wire.Message_Id,
    run_id_high:     wire.Run_Id,
    input_id_high:   wire.Input_Id,
    config_rev_high: wire.Config_Rev,
}

Session_History_Page_Row :: struct {
    message_id: wire.Message_Id,
    seq:        wire.Seq,
    payload:    string,
}

Open_Runs_Row :: struct {
    session_id:             wire.Session_Id,
    open_run_id:            wire.Run_Id,
    open_run_kind:          string,
    open_run_started_at_ms: u64,
}

Session_Page_Row :: struct {
    id:                 wire.Session_Id,
    workspace_id:       wire.Workspace_Id,
    origin:             string,
    parent_id:          Maybe(wire.Session_Id),
    parent_message_id:  Maybe(wire.Message_Id),
    parent_part_id:     Maybe(wire.Part_Id),
    source_id:          Maybe(wire.Session_Id),
    job_id:             Maybe(wire.Job_Id),
    profile:            string,
    model:              string,
    reasoning:          string,
    config_rev:         wire.Config_Rev,
    permission:         string,
    max_rounds:         Maybe(u64),
    title:              string,
    agent:              Maybe(string),
    created_by_name:    Maybe(string),
    created_by_version: Maybe(string),
    message_count:      u64,
    created_at_ms:      u64,
    updated_at_ms:      u64,
}

Session_Count_Row :: struct {
    total: u64,
}

Workspace_Page_Row :: struct {
    id:    wire.Workspace_Id,
    root:  string,
    title: string,
}

Delete_Catalog_Provider_Params :: struct {
    provider_id: string,
}

Clear_Catalog_Etag_Params :: struct {}

Catalog_Size_Params :: struct {}

Insert_Catalog_Provider_Params :: struct {
    provider_id:   string,
    models_dev_id: string,
    name:          string,
    base_url:      string,
    protocol:      string,
    etag:          Maybe(string),
}

Insert_Catalog_Provider_Env_Params :: struct {
    provider_id: string,
    ordinal:     int,
    name:        string,
}

Insert_Catalog_Model_Params :: struct {
    public_model_id:      string,
    provider_id:          string,
    upstream_id:          string,
    name:                 string,
    context_window:       u64,
    max_output_tokens:    u64,
    base_url:             string,
    protocol:             string,
    supports_temperature: bool,
    reasoning_replay:     string,
    thinking_format:      string,
    anthropic_adaptive:   bool,
    max_tokens_field:     string,
    reasoning_budget_min: Maybe(i64),
    reasoning_budget_max: Maybe(u64),
    supports_vision:      bool,
    supports_tools:       bool,
    cost_input:           f64,
    cost_output:          f64,
    cost_cache_read:      f64,
    cost_cache_write:     f64,
}

Insert_Catalog_Model_Level_Params :: struct {
    public_model_id: string,
    ordinal:         int,
    level:           string,
}

Clear_Configs_Params :: struct {
    session_id: wire.Session_Id,
}

Set_Session_Config_Params :: struct {
    config_rev: wire.Config_Rev,
    model:      string,
    reasoning:  string,
    session_id: wire.Session_Id,
}

Set_Prompt_Params :: struct {
    session_id: wire.Session_Id,
    prompt:     Maybe(string),
}

Session_Prompt_Params :: struct {
    session_id: wire.Session_Id,
}

Session_Config_Params :: struct {
    session_id:    wire.Session_Id,
    requested_rev: wire.Config_Rev,
}

Upsert_Api_Key_Params :: struct {
    provider_id: string,
    api_key:     string,
}

Upsert_OAuth_Params :: struct {
    provider_id:   string,
    access_token:  string,
    refresh_token: string,
    expires_at_ms: u64,
    account_id:    Maybe(string),
}

Remove_Credential_Params :: struct {
    provider_id: string,
}

Append_Event_Params :: struct {
    session_id: wire.Session_Id,
    seq:        wire.Seq,
    name:       string,
    payload:    string,
}

Advance_Seq_Params :: struct {
    seq:        wire.Seq,
    session_id: wire.Session_Id,
}

Bump_Ids_Params :: struct {
    message_id_high: wire.Message_Id,
    run_id_high:     wire.Run_Id,
    input_id_high:   wire.Input_Id,
    config_rev_high: wire.Config_Rev,
    session_id:      wire.Session_Id,
}

Read_High_Params :: struct {
    session_id: wire.Session_Id,
}

Truncate_Messages_Params :: struct {
    session_id:       wire.Session_Id,
    first_removed_id: wire.Message_Id,
}

Count_Messages_Params :: struct {
    delta:         i64,
    updated_at_ms: Maybe(u64),
    session_id:    wire.Session_Id,
}

Session_History_Page_Params :: struct {
    session_id:        wire.Session_Id,
    cursor_message_id: Maybe(wire.Message_Id),
    limit:             int,
}

Set_Open_Run_Params :: struct {
    open_run_id:            wire.Run_Id,
    open_run_kind:          string,
    open_run_started_at_ms: u64,
    session_id:             wire.Session_Id,
}

Clear_Open_Run_Params :: struct {
    session_id:  wire.Session_Id,
    open_run_id: wire.Run_Id,
}

Reset_Open_Run_Params :: struct {
    session_id: wire.Session_Id,
}

Open_Runs_Params :: struct {}

Session_Exists_Params :: struct {
    session_id: wire.Session_Id,
}

Session_Snapshot_Params :: struct {
    session_id: wire.Session_Id,
}

Session_Page_Params :: struct {
    filter_workspace_id:  Maybe(wire.Workspace_Id),
    parent_id:            Maybe(wire.Session_Id),
    job_id:               Maybe(wire.Job_Id),
    top_level:            bool,
    cursor_updated_at_ms: Maybe(u64),
    cursor_id:            Maybe(wire.Session_Id),
    limit:                int,
}

Session_Count_Params :: struct {
    workspace_id: Maybe(wire.Workspace_Id),
    parent_id:    Maybe(wire.Session_Id),
    job_id:       Maybe(wire.Job_Id),
    top_level:    bool,
}

Insert_Workspace_Params :: struct {
    id:    wire.Workspace_Id,
    root:  string,
    title: string,
}

Workspace_Page_Params :: struct {
    limit: int,
}

@(private)
Query_Id :: enum {
    Delete_Catalog_Provider,
    Clear_Catalog_Etag,
    Catalog_Size,
    Insert_Catalog_Provider,
    Insert_Catalog_Provider_Env,
    Insert_Catalog_Model,
    Insert_Catalog_Model_Level,
    Clear_Configs,
    Set_Session_Config,
    Set_Prompt,
    Session_Prompt,
    Session_Config,
    Upsert_Api_Key,
    Upsert_OAuth,
    Remove_Credential,
    Append_Event,
    Advance_Seq,
    Bump_Ids,
    Read_High,
    Truncate_Messages,
    Count_Messages,
    Session_History_Page,
    Set_Open_Run,
    Clear_Open_Run,
    Reset_Open_Run,
    Open_Runs,
    Session_Exists,
    Session_Snapshot,
    Session_Page,
    Session_Count,
    Insert_Workspace,
    Workspace_Page,
}

@(private, rodata)
QUERY_SQL := [Query_Id]string {
    .Delete_Catalog_Provider     = `DELETE FROM catalog_providers WHERE provider_id = :provider_id;`,
    .Clear_Catalog_Etag          = `UPDATE catalog_providers SET etag = NULL;`,
    .Catalog_Size                = `SELECT
    (SELECT count(*) FROM catalog_providers) AS providers,
    (SELECT count(*) FROM catalog_models) AS models;`,
    .Insert_Catalog_Provider     = `INSERT INTO catalog_providers(
    provider_id, models_dev_id, name, base_url, protocol, etag
)
VALUES (
    :provider_id, :models_dev_id, :name, :base_url, :protocol, :etag
);`,
    .Insert_Catalog_Provider_Env = `INSERT INTO catalog_provider_env(provider_id, ordinal, name)
VALUES (:provider_id, :ordinal, :name);`,
    .Insert_Catalog_Model        = `INSERT INTO catalog_models(
    public_model_id, provider_id,
    upstream_id, name, context_window, max_output_tokens,
    base_url, protocol, supports_temperature,
    reasoning_replay, thinking_format, anthropic_adaptive, max_tokens_field,
    reasoning_budget_min, reasoning_budget_max,
    supports_vision, supports_tools,
    cost_input, cost_output, cost_cache_read, cost_cache_write
)
VALUES (
    :public_model_id, :provider_id,
    :upstream_id, :name, :context_window, :max_output_tokens,
    :base_url, :protocol, :supports_temperature,
    :reasoning_replay, :thinking_format, :anthropic_adaptive, :max_tokens_field,
    :reasoning_budget_min, :reasoning_budget_max,
    :supports_vision, :supports_tools,
    :cost_input, :cost_output, :cost_cache_read, :cost_cache_write
);`,
    .Insert_Catalog_Model_Level  = `INSERT INTO catalog_model_reasoning_levels(public_model_id, ordinal, level)
VALUES (:public_model_id, :ordinal, :level);`,
    .Clear_Configs               = `DELETE FROM session_configs WHERE session_id = :session_id;`,
    .Set_Session_Config          = `UPDATE sessions
    SET config_rev = :config_rev, model = :model, reasoning = :reasoning
    WHERE id = :session_id;`,
    .Set_Prompt                  = `INSERT OR REPLACE INTO session_prompts(session_id, prompt)
    SELECT :session_id, :prompt WHERE :prompt IS NOT NULL;`,
    .Session_Prompt              = `SELECT prompt FROM session_prompts WHERE session_id = :session_id;`,
    .Session_Config              = `SELECT config_rev, model, reasoning FROM session_configs
    WHERE session_id = :session_id AND config_rev = :requested_rev;`,
    .Upsert_Api_Key              = `INSERT OR REPLACE INTO provider_credentials(provider_id, kind, api_key)
VALUES (:provider_id, 'api_key', :api_key);`,
    .Upsert_OAuth                = `INSERT OR REPLACE INTO provider_credentials(
    provider_id, kind, access_token, refresh_token, expires_at_ms, account_id
)
VALUES (
    :provider_id, 'oauth', :access_token, :refresh_token, :expires_at_ms, :account_id
);`,
    .Remove_Credential           = `DELETE FROM provider_credentials WHERE provider_id = :provider_id;`,
    .Append_Event                = `INSERT INTO events(session_id, seq, name, payload)
    VALUES (:session_id, :seq, :name, :payload);`,
    .Advance_Seq                 = `UPDATE sessions SET seq_high = :seq
    WHERE id = :session_id AND seq_high = :seq - 1;`,
    .Bump_Ids                    = `UPDATE sessions SET
    message_id_high = MAX(message_id_high, :message_id_high),
    run_id_high     = MAX(run_id_high, :run_id_high),
    input_id_high   = MAX(input_id_high, :input_id_high),
    config_rev_high = MAX(config_rev_high, :config_rev_high)
    WHERE id = :session_id;`,
    .Read_High                   = `SELECT seq_high, message_id_high, run_id_high, input_id_high, config_rev_high
    FROM sessions WHERE id = :session_id;`,
    .Truncate_Messages           = `DELETE FROM messages
    WHERE session_id = :session_id AND message_id >= :first_removed_id;`,
    .Count_Messages              = `UPDATE sessions SET
    message_count = message_count + :delta,
    updated_at_ms = MAX(updated_at_ms, COALESCE(:updated_at_ms, 0))
    WHERE id = :session_id;`,
    .Session_History_Page        = `SELECT m.message_id, m.seq, e.payload
    FROM messages m
    JOIN events e ON e.session_id = m.session_id AND e.seq = m.seq
    WHERE m.session_id = :session_id
      AND (:cursor_message_id IS NULL OR m.message_id < :cursor_message_id)
    ORDER BY m.message_id DESC
    LIMIT :limit;`,
    .Set_Open_Run                = `UPDATE sessions SET
    open_run_id            = :open_run_id,
    open_run_kind          = :open_run_kind,
    open_run_started_at_ms = :open_run_started_at_ms
    WHERE id = :session_id;`,
    .Clear_Open_Run              = `UPDATE sessions SET
    open_run_id            = NULL,
    open_run_kind          = NULL,
    open_run_started_at_ms = NULL
    WHERE id = :session_id AND open_run_id = :open_run_id;`,
    .Reset_Open_Run              = `UPDATE sessions SET
    open_run_id            = NULL,
    open_run_kind          = NULL,
    open_run_started_at_ms = NULL
    WHERE id = :session_id;`,
    .Open_Runs                   = `SELECT id AS session_id, open_run_id, open_run_kind, open_run_started_at_ms
FROM sessions
WHERE open_run_id IS NOT NULL
ORDER BY open_run_started_at_ms ASC, id ASC;`,
    .Session_Exists              = `SELECT 1 FROM sessions WHERE id = :session_id;`,
    .Session_Snapshot            = `SELECT
    id, workspace_id,
    origin, parent_id, parent_message_id, parent_part_id, source_id, job_id,
    profile, model, reasoning, config_rev, permission, max_rounds, title, agent,
    created_by_name, created_by_version,
    message_count, created_at_ms, updated_at_ms,
    open_run_id, open_run_kind, open_run_started_at_ms
FROM sessions
WHERE id = :session_id;`,
    .Session_Page                = `SELECT
    id, workspace_id,
    origin, parent_id, parent_message_id, parent_part_id, source_id, job_id,
    profile, model, reasoning, config_rev, permission, max_rounds, title, agent,
    created_by_name, created_by_version,
    message_count, created_at_ms, updated_at_ms
FROM sessions
WHERE (:filter_workspace_id IS NULL OR workspace_id = :filter_workspace_id)
  AND (:parent_id    IS NULL OR parent_id    = :parent_id)
  AND (:job_id       IS NULL OR job_id       = :job_id)
  AND (NOT :top_level OR origin IN ('root', 'fork'))
  AND (:cursor_updated_at_ms IS NULL
       OR updated_at_ms < :cursor_updated_at_ms
       OR (updated_at_ms = :cursor_updated_at_ms AND id < :cursor_id))
ORDER BY updated_at_ms DESC, id DESC
LIMIT :limit;`,
    .Session_Count               = `SELECT count(*) AS total FROM sessions
WHERE (:workspace_id IS NULL OR workspace_id = :workspace_id)
  AND (:parent_id    IS NULL OR parent_id    = :parent_id)
  AND (:job_id       IS NULL OR job_id       = :job_id)
  AND (NOT :top_level OR origin IN ('root', 'fork'));`,
    .Insert_Workspace            = `INSERT INTO workspaces(id, root, title) VALUES (:id, :root, :title)
    ON CONFLICT(id) DO NOTHING;`,
    .Workspace_Page              = `SELECT id, root, title FROM workspaces ORDER BY root LIMIT :limit;`,
}

Queries :: struct {
    delete_catalog_provider:     sqlite.Bind_Mapping(Delete_Catalog_Provider_Params),
    clear_catalog_etag:          sqlite.Bind_Mapping(Clear_Catalog_Etag_Params),
    catalog_size:                sqlite.Reader(Catalog_Size_Params, Catalog_Size_Row),
    insert_catalog_provider:     sqlite.Bind_Mapping(Insert_Catalog_Provider_Params),
    insert_catalog_provider_env: sqlite.Bind_Mapping(Insert_Catalog_Provider_Env_Params),
    insert_catalog_model:        sqlite.Bind_Mapping(Insert_Catalog_Model_Params),
    insert_catalog_model_level:  sqlite.Bind_Mapping(Insert_Catalog_Model_Level_Params),
    clear_configs:               sqlite.Bind_Mapping(Clear_Configs_Params),
    set_session_config:          sqlite.Bind_Mapping(Set_Session_Config_Params),
    set_prompt:                  sqlite.Bind_Mapping(Set_Prompt_Params),
    session_prompt:              sqlite.Reader(Session_Prompt_Params, Session_Prompt_Row),
    session_config:              sqlite.Reader(Session_Config_Params, Session_Config_Row),
    upsert_api_key:              sqlite.Bind_Mapping(Upsert_Api_Key_Params),
    upsert_oauth:                sqlite.Bind_Mapping(Upsert_OAuth_Params),
    remove_credential:           sqlite.Bind_Mapping(Remove_Credential_Params),
    append_event:                sqlite.Bind_Mapping(Append_Event_Params),
    advance_seq:                 sqlite.Bind_Mapping(Advance_Seq_Params),
    bump_ids:                    sqlite.Bind_Mapping(Bump_Ids_Params),
    read_high:                   sqlite.Reader(Read_High_Params, Read_High_Row),
    truncate_messages:           sqlite.Bind_Mapping(Truncate_Messages_Params),
    count_messages:              sqlite.Bind_Mapping(Count_Messages_Params),
    session_history_page:        sqlite.Reader(Session_History_Page_Params, Session_History_Page_Row),
    set_open_run:                sqlite.Bind_Mapping(Set_Open_Run_Params),
    clear_open_run:              sqlite.Bind_Mapping(Clear_Open_Run_Params),
    reset_open_run:              sqlite.Bind_Mapping(Reset_Open_Run_Params),
    open_runs:                   sqlite.Reader(Open_Runs_Params, Open_Runs_Row),
    session_exists:              sqlite.Bind_Mapping(Session_Exists_Params),
    session_snapshot:            sqlite.Reader(Session_Snapshot_Params, Session_Row),
    session_page:                sqlite.Reader(Session_Page_Params, Session_Page_Row),
    session_count:               sqlite.Reader(Session_Count_Params, Session_Count_Row),
    insert_workspace:            sqlite.Bind_Mapping(Insert_Workspace_Params),
    workspace_page:              sqlite.Reader(Workspace_Page_Params, Workspace_Page_Row),
}

queries_init :: proc(db: ^sqlite.Conn, queries: ^Queries, allocator := context.allocator) -> sqlite.Error {
    delete_catalog_provider_stmt := sqlite.prepare(db, QUERY_SQL[.Delete_Catalog_Provider]) or_return
    delete_catalog_provider_bind, delete_catalog_provider_bind_err := sqlite.bind_prepare(
        delete_catalog_provider_stmt,
        Delete_Catalog_Provider_Params,
    )
    assert(delete_catalog_provider_bind_err == .None, "generated statement matches its generated struct")
    queries.delete_catalog_provider = delete_catalog_provider_bind
    clear_catalog_etag_stmt := sqlite.prepare(db, QUERY_SQL[.Clear_Catalog_Etag]) or_return
    clear_catalog_etag_bind, clear_catalog_etag_bind_err := sqlite.bind_prepare(
        clear_catalog_etag_stmt,
        Clear_Catalog_Etag_Params,
    )
    assert(clear_catalog_etag_bind_err == .None, "generated statement matches its generated struct")
    queries.clear_catalog_etag = clear_catalog_etag_bind
    catalog_size_stmt := sqlite.prepare(db, QUERY_SQL[.Catalog_Size]) or_return
    catalog_size_reader, catalog_size_reader_err := sqlite.reader_prepare(
        catalog_size_stmt,
        Catalog_Size_Params,
        Catalog_Size_Row,
        allocator,
    )
    if catalog_size_reader_err == .Out_Of_Memory {
        sqlite.finalize(catalog_size_stmt)
        return catalog_size_reader_err
    }
    assert(catalog_size_reader_err == .None, "generated statement matches its generated struct")
    queries.catalog_size = catalog_size_reader
    insert_catalog_provider_stmt := sqlite.prepare(db, QUERY_SQL[.Insert_Catalog_Provider]) or_return
    insert_catalog_provider_bind, insert_catalog_provider_bind_err := sqlite.bind_prepare(
        insert_catalog_provider_stmt,
        Insert_Catalog_Provider_Params,
    )
    assert(insert_catalog_provider_bind_err == .None, "generated statement matches its generated struct")
    queries.insert_catalog_provider = insert_catalog_provider_bind
    insert_catalog_provider_env_stmt := sqlite.prepare(db, QUERY_SQL[.Insert_Catalog_Provider_Env]) or_return
    insert_catalog_provider_env_bind, insert_catalog_provider_env_bind_err := sqlite.bind_prepare(
        insert_catalog_provider_env_stmt,
        Insert_Catalog_Provider_Env_Params,
    )
    assert(insert_catalog_provider_env_bind_err == .None, "generated statement matches its generated struct")
    queries.insert_catalog_provider_env = insert_catalog_provider_env_bind
    insert_catalog_model_stmt := sqlite.prepare(db, QUERY_SQL[.Insert_Catalog_Model]) or_return
    insert_catalog_model_bind, insert_catalog_model_bind_err := sqlite.bind_prepare(
        insert_catalog_model_stmt,
        Insert_Catalog_Model_Params,
    )
    assert(insert_catalog_model_bind_err == .None, "generated statement matches its generated struct")
    queries.insert_catalog_model = insert_catalog_model_bind
    insert_catalog_model_level_stmt := sqlite.prepare(db, QUERY_SQL[.Insert_Catalog_Model_Level]) or_return
    insert_catalog_model_level_bind, insert_catalog_model_level_bind_err := sqlite.bind_prepare(
        insert_catalog_model_level_stmt,
        Insert_Catalog_Model_Level_Params,
    )
    assert(insert_catalog_model_level_bind_err == .None, "generated statement matches its generated struct")
    queries.insert_catalog_model_level = insert_catalog_model_level_bind
    clear_configs_stmt := sqlite.prepare(db, QUERY_SQL[.Clear_Configs]) or_return
    clear_configs_bind, clear_configs_bind_err := sqlite.bind_prepare(clear_configs_stmt, Clear_Configs_Params)
    assert(clear_configs_bind_err == .None, "generated statement matches its generated struct")
    queries.clear_configs = clear_configs_bind
    set_session_config_stmt := sqlite.prepare(db, QUERY_SQL[.Set_Session_Config]) or_return
    set_session_config_bind, set_session_config_bind_err := sqlite.bind_prepare(
        set_session_config_stmt,
        Set_Session_Config_Params,
    )
    assert(set_session_config_bind_err == .None, "generated statement matches its generated struct")
    queries.set_session_config = set_session_config_bind
    set_prompt_stmt := sqlite.prepare(db, QUERY_SQL[.Set_Prompt]) or_return
    set_prompt_bind, set_prompt_bind_err := sqlite.bind_prepare(set_prompt_stmt, Set_Prompt_Params)
    assert(set_prompt_bind_err == .None, "generated statement matches its generated struct")
    queries.set_prompt = set_prompt_bind
    session_prompt_stmt := sqlite.prepare(db, QUERY_SQL[.Session_Prompt]) or_return
    session_prompt_reader, session_prompt_reader_err := sqlite.reader_prepare(
        session_prompt_stmt,
        Session_Prompt_Params,
        Session_Prompt_Row,
        allocator,
    )
    if session_prompt_reader_err == .Out_Of_Memory {
        sqlite.finalize(session_prompt_stmt)
        return session_prompt_reader_err
    }
    assert(session_prompt_reader_err == .None, "generated statement matches its generated struct")
    queries.session_prompt = session_prompt_reader
    session_config_stmt := sqlite.prepare(db, QUERY_SQL[.Session_Config]) or_return
    session_config_reader, session_config_reader_err := sqlite.reader_prepare(
        session_config_stmt,
        Session_Config_Params,
        Session_Config_Row,
        allocator,
    )
    if session_config_reader_err == .Out_Of_Memory {
        sqlite.finalize(session_config_stmt)
        return session_config_reader_err
    }
    assert(session_config_reader_err == .None, "generated statement matches its generated struct")
    queries.session_config = session_config_reader
    upsert_api_key_stmt := sqlite.prepare(db, QUERY_SQL[.Upsert_Api_Key]) or_return
    upsert_api_key_bind, upsert_api_key_bind_err := sqlite.bind_prepare(upsert_api_key_stmt, Upsert_Api_Key_Params)
    assert(upsert_api_key_bind_err == .None, "generated statement matches its generated struct")
    queries.upsert_api_key = upsert_api_key_bind
    upsert_oauth_stmt := sqlite.prepare(db, QUERY_SQL[.Upsert_OAuth]) or_return
    upsert_oauth_bind, upsert_oauth_bind_err := sqlite.bind_prepare(upsert_oauth_stmt, Upsert_OAuth_Params)
    assert(upsert_oauth_bind_err == .None, "generated statement matches its generated struct")
    queries.upsert_oauth = upsert_oauth_bind
    remove_credential_stmt := sqlite.prepare(db, QUERY_SQL[.Remove_Credential]) or_return
    remove_credential_bind, remove_credential_bind_err := sqlite.bind_prepare(
        remove_credential_stmt,
        Remove_Credential_Params,
    )
    assert(remove_credential_bind_err == .None, "generated statement matches its generated struct")
    queries.remove_credential = remove_credential_bind
    append_event_stmt := sqlite.prepare(db, QUERY_SQL[.Append_Event]) or_return
    append_event_bind, append_event_bind_err := sqlite.bind_prepare(append_event_stmt, Append_Event_Params)
    assert(append_event_bind_err == .None, "generated statement matches its generated struct")
    queries.append_event = append_event_bind
    advance_seq_stmt := sqlite.prepare(db, QUERY_SQL[.Advance_Seq]) or_return
    advance_seq_bind, advance_seq_bind_err := sqlite.bind_prepare(advance_seq_stmt, Advance_Seq_Params)
    assert(advance_seq_bind_err == .None, "generated statement matches its generated struct")
    queries.advance_seq = advance_seq_bind
    bump_ids_stmt := sqlite.prepare(db, QUERY_SQL[.Bump_Ids]) or_return
    bump_ids_bind, bump_ids_bind_err := sqlite.bind_prepare(bump_ids_stmt, Bump_Ids_Params)
    assert(bump_ids_bind_err == .None, "generated statement matches its generated struct")
    queries.bump_ids = bump_ids_bind
    read_high_stmt := sqlite.prepare(db, QUERY_SQL[.Read_High]) or_return
    read_high_reader, read_high_reader_err := sqlite.reader_prepare(
        read_high_stmt,
        Read_High_Params,
        Read_High_Row,
        allocator,
    )
    if read_high_reader_err == .Out_Of_Memory {
        sqlite.finalize(read_high_stmt)
        return read_high_reader_err
    }
    assert(read_high_reader_err == .None, "generated statement matches its generated struct")
    queries.read_high = read_high_reader
    truncate_messages_stmt := sqlite.prepare(db, QUERY_SQL[.Truncate_Messages]) or_return
    truncate_messages_bind, truncate_messages_bind_err := sqlite.bind_prepare(
        truncate_messages_stmt,
        Truncate_Messages_Params,
    )
    assert(truncate_messages_bind_err == .None, "generated statement matches its generated struct")
    queries.truncate_messages = truncate_messages_bind
    count_messages_stmt := sqlite.prepare(db, QUERY_SQL[.Count_Messages]) or_return
    count_messages_bind, count_messages_bind_err := sqlite.bind_prepare(count_messages_stmt, Count_Messages_Params)
    assert(count_messages_bind_err == .None, "generated statement matches its generated struct")
    queries.count_messages = count_messages_bind
    session_history_page_stmt := sqlite.prepare(db, QUERY_SQL[.Session_History_Page]) or_return
    session_history_page_reader, session_history_page_reader_err := sqlite.reader_prepare(
        session_history_page_stmt,
        Session_History_Page_Params,
        Session_History_Page_Row,
        allocator,
    )
    if session_history_page_reader_err == .Out_Of_Memory {
        sqlite.finalize(session_history_page_stmt)
        return session_history_page_reader_err
    }
    assert(session_history_page_reader_err == .None, "generated statement matches its generated struct")
    queries.session_history_page = session_history_page_reader
    set_open_run_stmt := sqlite.prepare(db, QUERY_SQL[.Set_Open_Run]) or_return
    set_open_run_bind, set_open_run_bind_err := sqlite.bind_prepare(set_open_run_stmt, Set_Open_Run_Params)
    assert(set_open_run_bind_err == .None, "generated statement matches its generated struct")
    queries.set_open_run = set_open_run_bind
    clear_open_run_stmt := sqlite.prepare(db, QUERY_SQL[.Clear_Open_Run]) or_return
    clear_open_run_bind, clear_open_run_bind_err := sqlite.bind_prepare(clear_open_run_stmt, Clear_Open_Run_Params)
    assert(clear_open_run_bind_err == .None, "generated statement matches its generated struct")
    queries.clear_open_run = clear_open_run_bind
    reset_open_run_stmt := sqlite.prepare(db, QUERY_SQL[.Reset_Open_Run]) or_return
    reset_open_run_bind, reset_open_run_bind_err := sqlite.bind_prepare(reset_open_run_stmt, Reset_Open_Run_Params)
    assert(reset_open_run_bind_err == .None, "generated statement matches its generated struct")
    queries.reset_open_run = reset_open_run_bind
    open_runs_stmt := sqlite.prepare(db, QUERY_SQL[.Open_Runs]) or_return
    open_runs_reader, open_runs_reader_err := sqlite.reader_prepare(
        open_runs_stmt,
        Open_Runs_Params,
        Open_Runs_Row,
        allocator,
    )
    if open_runs_reader_err == .Out_Of_Memory {
        sqlite.finalize(open_runs_stmt)
        return open_runs_reader_err
    }
    assert(open_runs_reader_err == .None, "generated statement matches its generated struct")
    queries.open_runs = open_runs_reader
    session_exists_stmt := sqlite.prepare(db, QUERY_SQL[.Session_Exists]) or_return
    session_exists_bind, session_exists_bind_err := sqlite.bind_prepare(session_exists_stmt, Session_Exists_Params)
    assert(session_exists_bind_err == .None, "generated statement matches its generated struct")
    queries.session_exists = session_exists_bind
    session_snapshot_stmt := sqlite.prepare(db, QUERY_SQL[.Session_Snapshot]) or_return
    session_snapshot_reader, session_snapshot_reader_err := sqlite.reader_prepare(
        session_snapshot_stmt,
        Session_Snapshot_Params,
        Session_Row,
        allocator,
    )
    if session_snapshot_reader_err == .Out_Of_Memory {
        sqlite.finalize(session_snapshot_stmt)
        return session_snapshot_reader_err
    }
    assert(session_snapshot_reader_err == .None, "generated statement matches its generated struct")
    queries.session_snapshot = session_snapshot_reader
    session_page_stmt := sqlite.prepare(db, QUERY_SQL[.Session_Page]) or_return
    session_page_reader, session_page_reader_err := sqlite.reader_prepare(
        session_page_stmt,
        Session_Page_Params,
        Session_Page_Row,
        allocator,
    )
    if session_page_reader_err == .Out_Of_Memory {
        sqlite.finalize(session_page_stmt)
        return session_page_reader_err
    }
    assert(session_page_reader_err == .None, "generated statement matches its generated struct")
    queries.session_page = session_page_reader
    session_count_stmt := sqlite.prepare(db, QUERY_SQL[.Session_Count]) or_return
    session_count_reader, session_count_reader_err := sqlite.reader_prepare(
        session_count_stmt,
        Session_Count_Params,
        Session_Count_Row,
        allocator,
    )
    if session_count_reader_err == .Out_Of_Memory {
        sqlite.finalize(session_count_stmt)
        return session_count_reader_err
    }
    assert(session_count_reader_err == .None, "generated statement matches its generated struct")
    queries.session_count = session_count_reader
    insert_workspace_stmt := sqlite.prepare(db, QUERY_SQL[.Insert_Workspace]) or_return
    insert_workspace_bind, insert_workspace_bind_err := sqlite.bind_prepare(
        insert_workspace_stmt,
        Insert_Workspace_Params,
    )
    assert(insert_workspace_bind_err == .None, "generated statement matches its generated struct")
    queries.insert_workspace = insert_workspace_bind
    workspace_page_stmt := sqlite.prepare(db, QUERY_SQL[.Workspace_Page]) or_return
    workspace_page_reader, workspace_page_reader_err := sqlite.reader_prepare(
        workspace_page_stmt,
        Workspace_Page_Params,
        Workspace_Page_Row,
        allocator,
    )
    if workspace_page_reader_err == .Out_Of_Memory {
        sqlite.finalize(workspace_page_stmt)
        return workspace_page_reader_err
    }
    assert(workspace_page_reader_err == .None, "generated statement matches its generated struct")
    queries.workspace_page = workspace_page_reader
    return nil
}

queries_destroy :: proc(queries: ^Queries, allocator := context.allocator) {
    sqlite.finalize(queries.delete_catalog_provider.statement)
    sqlite.finalize(queries.clear_catalog_etag.statement)
    sqlite.finalize(queries.catalog_size.statement)
    sqlite.reader_destroy(&queries.catalog_size, allocator)
    sqlite.finalize(queries.insert_catalog_provider.statement)
    sqlite.finalize(queries.insert_catalog_provider_env.statement)
    sqlite.finalize(queries.insert_catalog_model.statement)
    sqlite.finalize(queries.insert_catalog_model_level.statement)
    sqlite.finalize(queries.clear_configs.statement)
    sqlite.finalize(queries.set_session_config.statement)
    sqlite.finalize(queries.set_prompt.statement)
    sqlite.finalize(queries.session_prompt.statement)
    sqlite.reader_destroy(&queries.session_prompt, allocator)
    sqlite.finalize(queries.session_config.statement)
    sqlite.reader_destroy(&queries.session_config, allocator)
    sqlite.finalize(queries.upsert_api_key.statement)
    sqlite.finalize(queries.upsert_oauth.statement)
    sqlite.finalize(queries.remove_credential.statement)
    sqlite.finalize(queries.append_event.statement)
    sqlite.finalize(queries.advance_seq.statement)
    sqlite.finalize(queries.bump_ids.statement)
    sqlite.finalize(queries.read_high.statement)
    sqlite.reader_destroy(&queries.read_high, allocator)
    sqlite.finalize(queries.truncate_messages.statement)
    sqlite.finalize(queries.count_messages.statement)
    sqlite.finalize(queries.session_history_page.statement)
    sqlite.reader_destroy(&queries.session_history_page, allocator)
    sqlite.finalize(queries.set_open_run.statement)
    sqlite.finalize(queries.clear_open_run.statement)
    sqlite.finalize(queries.reset_open_run.statement)
    sqlite.finalize(queries.open_runs.statement)
    sqlite.reader_destroy(&queries.open_runs, allocator)
    sqlite.finalize(queries.session_exists.statement)
    sqlite.finalize(queries.session_snapshot.statement)
    sqlite.reader_destroy(&queries.session_snapshot, allocator)
    sqlite.finalize(queries.session_page.statement)
    sqlite.reader_destroy(&queries.session_page, allocator)
    sqlite.finalize(queries.session_count.statement)
    sqlite.reader_destroy(&queries.session_count, allocator)
    sqlite.finalize(queries.insert_workspace.statement)
    sqlite.finalize(queries.workspace_page.statement)
    sqlite.reader_destroy(&queries.workspace_page, allocator)
}

delete_catalog_provider :: proc(q: ^Queries, params_in: Delete_Catalog_Provider_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.delete_catalog_provider, &params)
}

clear_catalog_etag :: proc(q: ^Queries, params_in: Clear_Catalog_Etag_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.clear_catalog_etag, &params)
}

catalog_size :: proc(
    q: ^Queries,
    params_in: Catalog_Size_Params,
    allocator := context.allocator,
) -> (
    Catalog_Size_Row,
    sqlite.Error,
) {
    params := params_in
    return sqlite.read_one(&q.catalog_size, &params, allocator)
}

insert_catalog_provider :: proc(q: ^Queries, params_in: Insert_Catalog_Provider_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.insert_catalog_provider, &params)
}

insert_catalog_provider_env :: proc(q: ^Queries, params_in: Insert_Catalog_Provider_Env_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.insert_catalog_provider_env, &params)
}

insert_catalog_model :: proc(q: ^Queries, params_in: Insert_Catalog_Model_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.insert_catalog_model, &params)
}

insert_catalog_model_level :: proc(q: ^Queries, params_in: Insert_Catalog_Model_Level_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.insert_catalog_model_level, &params)
}

clear_configs :: proc(q: ^Queries, params_in: Clear_Configs_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.clear_configs, &params)
}

set_session_config :: proc(q: ^Queries, params_in: Set_Session_Config_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.set_session_config, &params)
}

set_prompt :: proc(q: ^Queries, params_in: Set_Prompt_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.set_prompt, &params)
}

session_prompt :: proc(
    q: ^Queries,
    params_in: Session_Prompt_Params,
    allocator := context.allocator,
) -> (
    Session_Prompt_Row,
    sqlite.Error,
) {
    params := params_in
    return sqlite.read_one(&q.session_prompt, &params, allocator)
}

session_config :: proc(
    q: ^Queries,
    params_in: Session_Config_Params,
    allocator := context.allocator,
) -> (
    Session_Config_Row,
    sqlite.Error,
) {
    params := params_in
    return sqlite.read_one(&q.session_config, &params, allocator)
}

upsert_api_key :: proc(q: ^Queries, params_in: Upsert_Api_Key_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.upsert_api_key, &params)
}

upsert_oauth :: proc(q: ^Queries, params_in: Upsert_OAuth_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.upsert_oauth, &params)
}

remove_credential :: proc(q: ^Queries, params_in: Remove_Credential_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.remove_credential, &params)
}

append_event :: proc(q: ^Queries, params_in: Append_Event_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.append_event, &params)
}

advance_seq :: proc(q: ^Queries, params_in: Advance_Seq_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.advance_seq, &params)
}

bump_ids :: proc(q: ^Queries, params_in: Bump_Ids_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.bump_ids, &params)
}

truncate_messages :: proc(q: ^Queries, params_in: Truncate_Messages_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.truncate_messages, &params)
}

count_messages :: proc(q: ^Queries, params_in: Count_Messages_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.count_messages, &params)
}

session_history_page :: proc(
    q: ^Queries,
    params_in: Session_History_Page_Params,
    allocator := context.allocator,
    cap_hint := 0,
) -> (
    []Session_History_Page_Row,
    sqlite.Error,
) {
    params := params_in
    return sqlite.read_all(&q.session_history_page, &params, allocator, cap_hint)
}

set_open_run :: proc(q: ^Queries, params_in: Set_Open_Run_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.set_open_run, &params)
}

clear_open_run :: proc(q: ^Queries, params_in: Clear_Open_Run_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.clear_open_run, &params)
}

reset_open_run :: proc(q: ^Queries, params_in: Reset_Open_Run_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.reset_open_run, &params)
}

open_runs :: proc(
    q: ^Queries,
    params_in: Open_Runs_Params,
    allocator := context.allocator,
    cap_hint := 0,
) -> (
    []Open_Runs_Row,
    sqlite.Error,
) {
    params := params_in
    return sqlite.read_all(&q.open_runs, &params, allocator, cap_hint)
}

session_snapshot :: proc(
    q: ^Queries,
    params_in: Session_Snapshot_Params,
    allocator := context.allocator,
) -> (
    Session_Row,
    sqlite.Error,
) {
    params := params_in
    return sqlite.read_one(&q.session_snapshot, &params, allocator)
}

session_page :: proc(
    q: ^Queries,
    params_in: Session_Page_Params,
    allocator := context.allocator,
    cap_hint := 0,
) -> (
    []Session_Page_Row,
    sqlite.Error,
) {
    params := params_in
    return sqlite.read_all(&q.session_page, &params, allocator, cap_hint)
}

session_count :: proc(
    q: ^Queries,
    params_in: Session_Count_Params,
    allocator := context.allocator,
) -> (
    Session_Count_Row,
    sqlite.Error,
) {
    params := params_in
    return sqlite.read_one(&q.session_count, &params, allocator)
}

insert_workspace :: proc(q: ^Queries, params_in: Insert_Workspace_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.insert_workspace, &params)
}

workspace_page :: proc(
    q: ^Queries,
    params_in: Workspace_Page_Params,
    allocator := context.allocator,
    cap_hint := 0,
) -> (
    []Workspace_Page_Row,
    sqlite.Error,
) {
    params := params_in
    return sqlite.read_all(&q.workspace_page, &params, allocator, cap_hint)
}
