// Code generated by tools/sqlgen from src/daemon/store/migrations and
// src/daemon/store/queries. DO NOT EDIT.
// Regenerate with ./build.py sql.

package queries

import "src:wire"

import "libs:bindings/sqlite"

Create_Session_Params :: struct {
    id:                     wire.Session_Id,
    workspace_id:           wire.Workspace_Id,
    origin:                 string,
    parent_id:              Maybe(wire.Session_Id),
    parent_message_id:      Maybe(wire.Message_Id),
    parent_part_id:         Maybe(wire.Part_Id),
    source_id:              Maybe(wire.Session_Id),
    job_id:                 Maybe(wire.Job_Id),
    profile:                string,
    model:                  string,
    reasoning:              string,
    config_rev:             wire.Config_Rev,
    permission:             string,
    max_rounds:             Maybe(u64),
    title:                  string,
    agent:                  Maybe(string),
    created_by_name:        Maybe(string),
    created_by_version:     Maybe(string),
    created_at_ms:          u64,
    updated_at_ms:          u64,
    open_run_id:            Maybe(wire.Run_Id),
    open_run_kind:          Maybe(string),
    open_run_reason:        Maybe(string),
    open_run_config_rev:    Maybe(wire.Config_Rev),
    open_run_started_at_ms: Maybe(u64),
}

Session_Row :: struct {
    id:                     wire.Session_Id,
    workspace_id:           wire.Workspace_Id,
    origin:                 string,
    parent_id:              Maybe(wire.Session_Id),
    parent_message_id:      Maybe(wire.Message_Id),
    parent_part_id:         Maybe(wire.Part_Id),
    source_id:              Maybe(wire.Session_Id),
    job_id:                 Maybe(wire.Job_Id),
    profile:                string,
    model:                  string,
    reasoning:              string,
    config_rev:             wire.Config_Rev,
    permission:             string,
    max_rounds:             Maybe(u64),
    title:                  string,
    agent:                  Maybe(string),
    created_by_name:        Maybe(string),
    created_by_version:     Maybe(string),
    message_count:          u64,
    created_at_ms:          u64,
    updated_at_ms:          u64,
    open_run_id:            Maybe(wire.Run_Id),
    open_run_kind:          Maybe(string),
    open_run_reason:        Maybe(string),
    open_run_config_rev:    Maybe(wire.Config_Rev),
    open_run_started_at_ms: Maybe(u64),
}

Insert_Message_Params :: struct {
    session_id:         wire.Session_Id,
    message_id:         wire.Message_Id,
    seq:                wire.Seq,
    role:               string,
    run_id:             Maybe(wire.Run_Id),
    config_rev:         Maybe(wire.Config_Rev),
    model:              Maybe(string),
    protocol:           Maybe(string),
    finish:             Maybe(string),
    tokens_input:       Maybe(u64),
    tokens_output:      Maybe(u64),
    tokens_reasoning:   Maybe(u64),
    tokens_cache_read:  Maybe(u64),
    tokens_cache_write: Maybe(u64),
    cost:               Maybe(f64),
    created_at_ms:      u64,
}

Insert_Config_Params :: struct {
    session_id: wire.Session_Id,
    config_rev: wire.Config_Rev,
    model:      string,
    reasoning:  string,
}

Session_Configs_Row :: struct {
    config_rev: wire.Config_Rev,
    model:      string,
    reasoning:  string,
}

Read_High_Row :: struct {
    seq_high:        wire.Seq,
    message_id_high: wire.Message_Id,
    run_id_high:     wire.Run_Id,
    input_id_high:   wire.Input_Id,
    config_rev_high: wire.Config_Rev,
}

Session_History_Page_Row :: struct {
    message_id: wire.Message_Id,
    seq:        wire.Seq,
    payload:    string,
}

Session_Page_Row :: struct {
    id:                 wire.Session_Id,
    workspace_id:       wire.Workspace_Id,
    origin:             string,
    parent_id:          Maybe(wire.Session_Id),
    parent_message_id:  Maybe(wire.Message_Id),
    parent_part_id:     Maybe(wire.Part_Id),
    source_id:          Maybe(wire.Session_Id),
    job_id:             Maybe(wire.Job_Id),
    profile:            string,
    model:              string,
    reasoning:          string,
    config_rev:         wire.Config_Rev,
    permission:         string,
    max_rounds:         Maybe(u64),
    title:              string,
    agent:              Maybe(string),
    created_by_name:    Maybe(string),
    created_by_version: Maybe(string),
    message_count:      u64,
    created_at_ms:      u64,
    updated_at_ms:      u64,
}

Session_Count_Row :: struct {
    total: u64,
}

Session_Activity_Row :: struct {
    message_count:          u64,
    open_run_id:            Maybe(wire.Run_Id),
    open_run_kind:          Maybe(string),
    open_run_reason:        Maybe(string),
    open_run_config_rev:    Maybe(wire.Config_Rev),
    open_run_started_at_ms: Maybe(u64),
}

Clear_Configs_Params :: struct {
    session_id: wire.Session_Id,
}

Set_Prompt_Params :: struct {
    session_id: wire.Session_Id,
    prompt:     Maybe(string),
}

Session_Configs_Params :: struct {
    session_id: wire.Session_Id,
}

Append_Event_Params :: struct {
    session_id: wire.Session_Id,
    seq:        wire.Seq,
    name:       string,
    payload:    string,
}

Advance_Seq_Params :: struct {
    seq:        wire.Seq,
    session_id: wire.Session_Id,
}

Bump_Ids_Params :: struct {
    message_id_high: wire.Message_Id,
    run_id_high:     wire.Run_Id,
    input_id_high:   wire.Input_Id,
    config_rev_high: wire.Config_Rev,
    session_id:      wire.Session_Id,
}

Read_High_Params :: struct {
    session_id: wire.Session_Id,
}

Truncate_Messages_Params :: struct {
    session_id:       wire.Session_Id,
    first_removed_id: wire.Message_Id,
}

Count_Messages_Params :: struct {
    delta:         i64,
    updated_at_ms: Maybe(u64),
    session_id:    wire.Session_Id,
}

Session_History_Page_Params :: struct {
    session_id:        wire.Session_Id,
    cursor_message_id: Maybe(wire.Message_Id),
    limit:             int,
}

Set_Open_Run_Params :: struct {
    open_run_id:            wire.Run_Id,
    open_run_kind:          string,
    open_run_reason:        Maybe(string),
    open_run_config_rev:    wire.Config_Rev,
    open_run_started_at_ms: u64,
    session_id:             wire.Session_Id,
}

Clear_Open_Run_Params :: struct {
    session_id:  wire.Session_Id,
    open_run_id: wire.Run_Id,
}

Reset_Open_Run_Params :: struct {
    session_id: wire.Session_Id,
}

Session_Exists_Params :: struct {
    session_id: wire.Session_Id,
}

Session_Page_Params :: struct {
    filter_workspace_id:  Maybe(wire.Workspace_Id),
    parent_id:            Maybe(wire.Session_Id),
    job_id:               Maybe(wire.Job_Id),
    top_level:            bool,
    cursor_updated_at_ms: Maybe(u64),
    cursor_id:            Maybe(wire.Session_Id),
    limit:                int,
}

Session_Count_Params :: struct {
    workspace_id: Maybe(wire.Workspace_Id),
    parent_id:    Maybe(wire.Session_Id),
    job_id:       Maybe(wire.Job_Id),
    top_level:    bool,
}

Session_Activity_Params :: struct {
    session_id: wire.Session_Id,
}

@(private)
Query_Id :: enum {
    Clear_Configs,
    Set_Prompt,
    Session_Configs,
    Append_Event,
    Advance_Seq,
    Bump_Ids,
    Read_High,
    Truncate_Messages,
    Count_Messages,
    Session_History_Page,
    Set_Open_Run,
    Clear_Open_Run,
    Reset_Open_Run,
    Session_Exists,
    Session_Page,
    Session_Count,
    Session_Activity,
}

@(private, rodata)
QUERY_SQL := [Query_Id]string {
    .Clear_Configs        = `DELETE FROM session_configs WHERE session_id = :session_id;`,
    .Set_Prompt           = `INSERT OR REPLACE INTO session_prompts(session_id, prompt)
    SELECT :session_id, :prompt WHERE :prompt IS NOT NULL;`,
    .Session_Configs      = `SELECT config_rev, model, reasoning FROM session_configs
    WHERE session_id = :session_id
    ORDER BY config_rev;`,
    .Append_Event         = `INSERT INTO events(session_id, seq, name, payload)
    VALUES (:session_id, :seq, :name, :payload);`,
    .Advance_Seq          = `UPDATE sessions SET seq_high = :seq
    WHERE id = :session_id AND seq_high = :seq - 1;`,
    .Bump_Ids             = `UPDATE sessions SET
    message_id_high = MAX(message_id_high, :message_id_high),
    run_id_high     = MAX(run_id_high, :run_id_high),
    input_id_high   = MAX(input_id_high, :input_id_high),
    config_rev_high = MAX(config_rev_high, :config_rev_high)
    WHERE id = :session_id;`,
    .Read_High            = `SELECT seq_high, message_id_high, run_id_high, input_id_high, config_rev_high
    FROM sessions WHERE id = :session_id;`,
    .Truncate_Messages    = `DELETE FROM messages
    WHERE session_id = :session_id AND message_id >= :first_removed_id;`,
    .Count_Messages       = `UPDATE sessions SET
    message_count = message_count + :delta,
    updated_at_ms = MAX(updated_at_ms, COALESCE(:updated_at_ms, 0))
    WHERE id = :session_id;`,
    .Session_History_Page = `SELECT m.message_id, m.seq, e.payload
    FROM messages m
    JOIN events e ON e.session_id = m.session_id AND e.seq = m.seq
    WHERE m.session_id = :session_id
      AND (:cursor_message_id IS NULL OR m.message_id < :cursor_message_id)
    ORDER BY m.message_id DESC
    LIMIT :limit;`,
    .Set_Open_Run         = `UPDATE sessions SET
    open_run_id            = :open_run_id,
    open_run_kind          = :open_run_kind,
    open_run_reason        = :open_run_reason,
    open_run_config_rev    = :open_run_config_rev,
    open_run_started_at_ms = :open_run_started_at_ms
    WHERE id = :session_id;`,
    .Clear_Open_Run       = `UPDATE sessions SET
    open_run_id            = NULL,
    open_run_kind          = NULL,
    open_run_reason        = NULL,
    open_run_config_rev    = NULL,
    open_run_started_at_ms = NULL
    WHERE id = :session_id AND open_run_id = :open_run_id;`,
    .Reset_Open_Run       = `UPDATE sessions SET
    open_run_id            = NULL,
    open_run_kind          = NULL,
    open_run_reason        = NULL,
    open_run_config_rev    = NULL,
    open_run_started_at_ms = NULL
    WHERE id = :session_id;`,
    .Session_Exists       = `SELECT 1 FROM sessions WHERE id = :session_id;`,
    .Session_Page         = `SELECT
    id, workspace_id,
    origin, parent_id, parent_message_id, parent_part_id, source_id, job_id,
    profile, model, reasoning, config_rev, permission, max_rounds, title, agent,
    created_by_name, created_by_version,
    message_count, created_at_ms, updated_at_ms
FROM sessions
WHERE (:filter_workspace_id IS NULL OR workspace_id = :filter_workspace_id)
  AND (:parent_id    IS NULL OR parent_id    = :parent_id)
  AND (:job_id       IS NULL OR job_id       = :job_id)
  AND (NOT :top_level OR origin IN ('root', 'fork'))
  AND (:cursor_updated_at_ms IS NULL
       OR updated_at_ms < :cursor_updated_at_ms
       OR (updated_at_ms = :cursor_updated_at_ms AND id < :cursor_id))
ORDER BY updated_at_ms DESC, id DESC
LIMIT :limit;`,
    .Session_Count        = `SELECT count(*) AS total FROM sessions
WHERE (:workspace_id IS NULL OR workspace_id = :workspace_id)
  AND (:parent_id    IS NULL OR parent_id    = :parent_id)
  AND (:job_id       IS NULL OR job_id       = :job_id)
  AND (NOT :top_level OR origin IN ('root', 'fork'));`,
    .Session_Activity     = `SELECT message_count,
       open_run_id, open_run_kind, open_run_reason, open_run_config_rev, open_run_started_at_ms
    FROM sessions WHERE id = :session_id;`,
}

Queries :: struct {
    clear_configs:        sqlite.Bind_Mapping(Clear_Configs_Params),
    set_prompt:           sqlite.Bind_Mapping(Set_Prompt_Params),
    session_configs:      sqlite.Reader(Session_Configs_Params, Session_Configs_Row),
    append_event:         sqlite.Bind_Mapping(Append_Event_Params),
    advance_seq:          sqlite.Bind_Mapping(Advance_Seq_Params),
    bump_ids:             sqlite.Bind_Mapping(Bump_Ids_Params),
    read_high:            sqlite.Reader(Read_High_Params, Read_High_Row),
    truncate_messages:    sqlite.Bind_Mapping(Truncate_Messages_Params),
    count_messages:       sqlite.Bind_Mapping(Count_Messages_Params),
    session_history_page: sqlite.Reader(Session_History_Page_Params, Session_History_Page_Row),
    set_open_run:         sqlite.Bind_Mapping(Set_Open_Run_Params),
    clear_open_run:       sqlite.Bind_Mapping(Clear_Open_Run_Params),
    reset_open_run:       sqlite.Bind_Mapping(Reset_Open_Run_Params),
    session_exists:       sqlite.Bind_Mapping(Session_Exists_Params),
    session_page:         sqlite.Reader(Session_Page_Params, Session_Page_Row),
    session_count:        sqlite.Reader(Session_Count_Params, Session_Count_Row),
    session_activity:     sqlite.Reader(Session_Activity_Params, Session_Activity_Row),
}

queries_init :: proc(db: ^sqlite.Conn, queries: ^Queries, allocator := context.allocator) -> sqlite.Error {
    clear_configs_stmt := sqlite.prepare(db, QUERY_SQL[.Clear_Configs]) or_return
    clear_configs_bind, clear_configs_bind_err := sqlite.bind_prepare(clear_configs_stmt, Clear_Configs_Params)
    assert(clear_configs_bind_err == .None, "generated statement matches its generated struct")
    queries.clear_configs = clear_configs_bind
    set_prompt_stmt := sqlite.prepare(db, QUERY_SQL[.Set_Prompt]) or_return
    set_prompt_bind, set_prompt_bind_err := sqlite.bind_prepare(set_prompt_stmt, Set_Prompt_Params)
    assert(set_prompt_bind_err == .None, "generated statement matches its generated struct")
    queries.set_prompt = set_prompt_bind
    session_configs_stmt := sqlite.prepare(db, QUERY_SQL[.Session_Configs]) or_return
    session_configs_reader, session_configs_reader_err := sqlite.reader_prepare(
        session_configs_stmt,
        Session_Configs_Params,
        Session_Configs_Row,
        allocator,
    )
    if session_configs_reader_err == .Out_Of_Memory {
        sqlite.finalize(session_configs_stmt)
        return session_configs_reader_err
    }
    assert(session_configs_reader_err == .None, "generated statement matches its generated struct")
    queries.session_configs = session_configs_reader
    append_event_stmt := sqlite.prepare(db, QUERY_SQL[.Append_Event]) or_return
    append_event_bind, append_event_bind_err := sqlite.bind_prepare(append_event_stmt, Append_Event_Params)
    assert(append_event_bind_err == .None, "generated statement matches its generated struct")
    queries.append_event = append_event_bind
    advance_seq_stmt := sqlite.prepare(db, QUERY_SQL[.Advance_Seq]) or_return
    advance_seq_bind, advance_seq_bind_err := sqlite.bind_prepare(advance_seq_stmt, Advance_Seq_Params)
    assert(advance_seq_bind_err == .None, "generated statement matches its generated struct")
    queries.advance_seq = advance_seq_bind
    bump_ids_stmt := sqlite.prepare(db, QUERY_SQL[.Bump_Ids]) or_return
    bump_ids_bind, bump_ids_bind_err := sqlite.bind_prepare(bump_ids_stmt, Bump_Ids_Params)
    assert(bump_ids_bind_err == .None, "generated statement matches its generated struct")
    queries.bump_ids = bump_ids_bind
    read_high_stmt := sqlite.prepare(db, QUERY_SQL[.Read_High]) or_return
    read_high_reader, read_high_reader_err := sqlite.reader_prepare(
        read_high_stmt,
        Read_High_Params,
        Read_High_Row,
        allocator,
    )
    if read_high_reader_err == .Out_Of_Memory {
        sqlite.finalize(read_high_stmt)
        return read_high_reader_err
    }
    assert(read_high_reader_err == .None, "generated statement matches its generated struct")
    queries.read_high = read_high_reader
    truncate_messages_stmt := sqlite.prepare(db, QUERY_SQL[.Truncate_Messages]) or_return
    truncate_messages_bind, truncate_messages_bind_err := sqlite.bind_prepare(
        truncate_messages_stmt,
        Truncate_Messages_Params,
    )
    assert(truncate_messages_bind_err == .None, "generated statement matches its generated struct")
    queries.truncate_messages = truncate_messages_bind
    count_messages_stmt := sqlite.prepare(db, QUERY_SQL[.Count_Messages]) or_return
    count_messages_bind, count_messages_bind_err := sqlite.bind_prepare(count_messages_stmt, Count_Messages_Params)
    assert(count_messages_bind_err == .None, "generated statement matches its generated struct")
    queries.count_messages = count_messages_bind
    session_history_page_stmt := sqlite.prepare(db, QUERY_SQL[.Session_History_Page]) or_return
    session_history_page_reader, session_history_page_reader_err := sqlite.reader_prepare(
        session_history_page_stmt,
        Session_History_Page_Params,
        Session_History_Page_Row,
        allocator,
    )
    if session_history_page_reader_err == .Out_Of_Memory {
        sqlite.finalize(session_history_page_stmt)
        return session_history_page_reader_err
    }
    assert(session_history_page_reader_err == .None, "generated statement matches its generated struct")
    queries.session_history_page = session_history_page_reader
    set_open_run_stmt := sqlite.prepare(db, QUERY_SQL[.Set_Open_Run]) or_return
    set_open_run_bind, set_open_run_bind_err := sqlite.bind_prepare(set_open_run_stmt, Set_Open_Run_Params)
    assert(set_open_run_bind_err == .None, "generated statement matches its generated struct")
    queries.set_open_run = set_open_run_bind
    clear_open_run_stmt := sqlite.prepare(db, QUERY_SQL[.Clear_Open_Run]) or_return
    clear_open_run_bind, clear_open_run_bind_err := sqlite.bind_prepare(clear_open_run_stmt, Clear_Open_Run_Params)
    assert(clear_open_run_bind_err == .None, "generated statement matches its generated struct")
    queries.clear_open_run = clear_open_run_bind
    reset_open_run_stmt := sqlite.prepare(db, QUERY_SQL[.Reset_Open_Run]) or_return
    reset_open_run_bind, reset_open_run_bind_err := sqlite.bind_prepare(reset_open_run_stmt, Reset_Open_Run_Params)
    assert(reset_open_run_bind_err == .None, "generated statement matches its generated struct")
    queries.reset_open_run = reset_open_run_bind
    session_exists_stmt := sqlite.prepare(db, QUERY_SQL[.Session_Exists]) or_return
    session_exists_bind, session_exists_bind_err := sqlite.bind_prepare(session_exists_stmt, Session_Exists_Params)
    assert(session_exists_bind_err == .None, "generated statement matches its generated struct")
    queries.session_exists = session_exists_bind
    session_page_stmt := sqlite.prepare(db, QUERY_SQL[.Session_Page]) or_return
    session_page_reader, session_page_reader_err := sqlite.reader_prepare(
        session_page_stmt,
        Session_Page_Params,
        Session_Page_Row,
        allocator,
    )
    if session_page_reader_err == .Out_Of_Memory {
        sqlite.finalize(session_page_stmt)
        return session_page_reader_err
    }
    assert(session_page_reader_err == .None, "generated statement matches its generated struct")
    queries.session_page = session_page_reader
    session_count_stmt := sqlite.prepare(db, QUERY_SQL[.Session_Count]) or_return
    session_count_reader, session_count_reader_err := sqlite.reader_prepare(
        session_count_stmt,
        Session_Count_Params,
        Session_Count_Row,
        allocator,
    )
    if session_count_reader_err == .Out_Of_Memory {
        sqlite.finalize(session_count_stmt)
        return session_count_reader_err
    }
    assert(session_count_reader_err == .None, "generated statement matches its generated struct")
    queries.session_count = session_count_reader
    session_activity_stmt := sqlite.prepare(db, QUERY_SQL[.Session_Activity]) or_return
    session_activity_reader, session_activity_reader_err := sqlite.reader_prepare(
        session_activity_stmt,
        Session_Activity_Params,
        Session_Activity_Row,
        allocator,
    )
    if session_activity_reader_err == .Out_Of_Memory {
        sqlite.finalize(session_activity_stmt)
        return session_activity_reader_err
    }
    assert(session_activity_reader_err == .None, "generated statement matches its generated struct")
    queries.session_activity = session_activity_reader
    return nil
}

queries_destroy :: proc(queries: ^Queries, allocator := context.allocator) {
    sqlite.finalize(queries.clear_configs.statement)
    sqlite.finalize(queries.set_prompt.statement)
    sqlite.finalize(queries.session_configs.statement)
    sqlite.reader_destroy(&queries.session_configs, allocator)
    sqlite.finalize(queries.append_event.statement)
    sqlite.finalize(queries.advance_seq.statement)
    sqlite.finalize(queries.bump_ids.statement)
    sqlite.finalize(queries.read_high.statement)
    sqlite.reader_destroy(&queries.read_high, allocator)
    sqlite.finalize(queries.truncate_messages.statement)
    sqlite.finalize(queries.count_messages.statement)
    sqlite.finalize(queries.session_history_page.statement)
    sqlite.reader_destroy(&queries.session_history_page, allocator)
    sqlite.finalize(queries.set_open_run.statement)
    sqlite.finalize(queries.clear_open_run.statement)
    sqlite.finalize(queries.reset_open_run.statement)
    sqlite.finalize(queries.session_exists.statement)
    sqlite.finalize(queries.session_page.statement)
    sqlite.reader_destroy(&queries.session_page, allocator)
    sqlite.finalize(queries.session_count.statement)
    sqlite.reader_destroy(&queries.session_count, allocator)
    sqlite.finalize(queries.session_activity.statement)
    sqlite.reader_destroy(&queries.session_activity, allocator)
}

clear_configs :: proc(q: ^Queries, params_in: Clear_Configs_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.clear_configs, &params)
}

set_prompt :: proc(q: ^Queries, params_in: Set_Prompt_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.set_prompt, &params)
}

session_configs :: proc(
    q: ^Queries,
    params_in: Session_Configs_Params,
    allocator := context.allocator,
) -> (
    []Session_Configs_Row,
    sqlite.Error,
) {
    params := params_in
    return sqlite.read_all(&q.session_configs, &params, allocator)
}

append_event :: proc(q: ^Queries, params_in: Append_Event_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.append_event, &params)
}

advance_seq :: proc(q: ^Queries, params_in: Advance_Seq_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.advance_seq, &params)
}

bump_ids :: proc(q: ^Queries, params_in: Bump_Ids_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.bump_ids, &params)
}

truncate_messages :: proc(q: ^Queries, params_in: Truncate_Messages_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.truncate_messages, &params)
}

count_messages :: proc(q: ^Queries, params_in: Count_Messages_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.count_messages, &params)
}

session_history_page :: proc(
    q: ^Queries,
    params_in: Session_History_Page_Params,
    allocator := context.allocator,
) -> (
    []Session_History_Page_Row,
    sqlite.Error,
) {
    params := params_in
    return sqlite.read_all(&q.session_history_page, &params, allocator)
}

set_open_run :: proc(q: ^Queries, params_in: Set_Open_Run_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.set_open_run, &params)
}

clear_open_run :: proc(q: ^Queries, params_in: Clear_Open_Run_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.clear_open_run, &params)
}

reset_open_run :: proc(q: ^Queries, params_in: Reset_Open_Run_Params) -> sqlite.Result {
    params := params_in
    return sqlite.execute(&q.reset_open_run, &params)
}

session_page :: proc(
    q: ^Queries,
    params_in: Session_Page_Params,
    allocator := context.allocator,
) -> (
    []Session_Page_Row,
    sqlite.Error,
) {
    params := params_in
    return sqlite.read_all(&q.session_page, &params, allocator)
}

session_count :: proc(
    q: ^Queries,
    params_in: Session_Count_Params,
    allocator := context.allocator,
) -> (
    Session_Count_Row,
    sqlite.Error,
) {
    params := params_in
    return sqlite.read_one(&q.session_count, &params, allocator)
}

session_activity :: proc(
    q: ^Queries,
    params_in: Session_Activity_Params,
    allocator := context.allocator,
) -> (
    Session_Activity_Row,
    sqlite.Error,
) {
    params := params_in
    return sqlite.read_one(&q.session_activity, &params, allocator)
}
