package sqlgen

import "core:fmt"
import "core:strings"

import "tools:gen"

QUERIES_HEADER :: `// Code generated by tools/sqlgen from src/daemon/store/migrations and
// src/daemon/store/queries. DO NOT EDIT.
// Regenerate with ./build.py sql.

package queries

import "src:wire"

import "libs:bindings/sqlite"

`

// One candidate struct before dedup: a schema shape or a query's row, reduced
// to the same (name, fields) shape so both sources can be fingerprinted and
// compared uniformly. Params structs are never dedup candidates — see
// `generate_queries`.
@(private)
Struct_Def :: struct {
    name:        string,
    fields:      []Resolved_Field,

    // Whether `fields` was allocated for this def (a schema shape's, via
    // `shape_fields`) rather than borrowed from a `Resolved_Query` the caller
    // still owns — only the former is this function's to free.
    owns_fields: bool,
}

// Build queries_gen.odin's full text: every configured schema shape's struct,
// every resolved query's Params/Row structs, a Query_Id enum, its SQL table, the
// Queries registry (one `Bind_Mapping`/`Reader` field per query), `queries_init`/
// `queries_destroy`, and a thin wrapper procedure for every non-`:manual` query.
// Nothing here depends on `store` — a wrapper takes `^Queries`, not `^Store`, and
// returns the raw SQLite result, so this package has no knowledge of the caller's
// own error type.
generate_queries :: proc(
    shapes: []Shape,
    columns_by_table: map[string][]Column,
    sources: map[string]string,
    resolved: []Resolved_Query,
    d: ^gen.Diags,
    allocator := context.allocator,
) -> (
    data: []byte,
    ok: bool,
) {
    assert(d != nil, "generate_queries needs a diagnostic sink")

    b := strings.builder_make(allocator)
    strings.write_string(&b, QUERIES_HEADER)

    all_ok := true

    // Only structs that represent an entity's shape — a schema shape or a
    // query's result row — are dedup-eligible. Params structs never dedup
    // against each other: two queries can easily share a trivial shape (a lone
    // `session_id`) by pure accident, and merging those would make an
    // unrelated query's hand-written call site reference a confusingly-named,
    // iteration-order-dependent survivor for no real gain.
    identity_defs := make([dynamic]Struct_Def, 0, allocator)

    for shape in shapes {
        columns, have_table := columns_by_table[shape.table]

        if !have_table {
            gen.diagf(d, gen.Pos{}, "%s: no such table for shape %s", shape.table, shape.name)
            all_ok = false

            continue
        }

        fields, fields_ok := shape_fields(shape, columns, sources, d, allocator)

        if !fields_ok {
            all_ok = false

            continue
        }

        append(&identity_defs, Struct_Def{name = shape.name, fields = fields, owns_fields = true})
    }

    for q in resolved {
        if len(q.row) > 0 {
            append(&identity_defs, Struct_Def{name = fmt.tprintf("%s_Row", q.def.name), fields = q.row})
        }
    }

    alias := dedup_structs(identity_defs[:], allocator)
    defer delete(alias)

    for def in identity_defs {
        if _, aliased := alias[def.name]; !aliased {
            emit_field_struct(&b, def.name, def.fields)
        }

        if def.owns_fields {
            delete(def.fields, allocator)
        }
    }

    delete(identity_defs)

    for q in resolved {
        emit_field_struct(&b, fmt.tprintf("%s_Params", q.def.name), q.params)
    }

    emit_query_id_enum(&b, resolved)
    emit_query_sql_table(&b, resolved)
    emit_queries_registry(&b, resolved, alias)
    emit_queries_init(&b, resolved, alias)
    emit_queries_destroy(&b, resolved)

    for q in resolved {
        emit_query_wrapper(&b, q, alias)
    }

    if !all_ok {
        strings.builder_destroy(&b)

        return nil, false
    }

    return b.buf[:], true
}

// A shape's or query's field list, as text: enough to tell whether two
// independently-derived structs are interchangeable. Field order matters, same
// as struct layout does — two structs whose fields agree in name, type, and
// required-ness but in a different order are not considered the same shape.
@(private)
struct_fingerprint :: proc(fields: []Resolved_Field, allocator := context.temp_allocator) -> string {
    b := strings.builder_make(allocator)

    for f in fields {
        fmt.sbprintf(&b, "%s|%s|%t;", f.name, f.odin_type, f.required)
    }

    return strings.to_string(b)
}

// Map every struct whose fields exactly match an earlier one (a query selecting
// a table's full row, most commonly) to that earlier struct's name, so the
// caller emits one declaration instead of two identical ones. Shapes are
// collected before queries in `defs`, so a schema shape's name always wins over
// a query-specific one when both describe the same fields.
@(private)
dedup_structs :: proc(defs: []Struct_Def, allocator := context.allocator) -> (alias: map[string]string) {
    alias = make(map[string]string, allocator)
    canonical_by_fingerprint := make(map[string]string, context.temp_allocator)

    for def in defs {
        fp := struct_fingerprint(def.fields)

        if canonical, dup := canonical_by_fingerprint[fp]; dup {
            alias[def.name] = canonical
        } else {
            canonical_by_fingerprint[fp] = def.name
        }
    }

    return alias
}

// The name a reference to `name` should actually use — its dedup canonical name
// if one absorbed it, else `name` itself.
@(private)
resolved_name :: proc(alias: map[string]string, name: string) -> string {
    if canonical, aliased := alias[name]; aliased {
        return canonical
    }

    return name
}

@(private)
emit_field_struct :: proc(b: ^strings.Builder, name: string, fields: []Resolved_Field) {
    fmt.sbprintfln(b, "%s :: struct {{", name)

    for f in fields {
        emit_struct_field(b, f.name, f.odin_type, f.required)
    }

    fmt.sbprintln(b, "}")
    fmt.sbprintln(b)
}

@(private)
emit_query_id_enum :: proc(b: ^strings.Builder, resolved: []Resolved_Query) {
    fmt.sbprintln(b, "@(private)")
    fmt.sbprintln(b, "Query_Id :: enum {")

    for q in resolved {
        fmt.sbprintfln(b, "    %s,", q.def.name)
    }

    fmt.sbprintln(b, "}")
    fmt.sbprintln(b)
}

@(private)
emit_query_sql_table :: proc(b: ^strings.Builder, resolved: []Resolved_Query) {
    fmt.sbprintln(b, "@(private, rodata)")
    fmt.sbprintln(b, "QUERY_SQL := [Query_Id]string{")

    for q in resolved {
        fmt.sbprintfln(b, "    .%s = `%s`,", q.def.name, q.def.sql)
    }

    fmt.sbprintln(b, "}")
    fmt.sbprintln(b)
}

// One field per query: `Bind_Mapping(Params)` when it has no row (an `:exec`, or
// a `:manual` existence check), `Reader(Params, Row)` when it does — `:manual`
// queries with a row (like `Read_High`) reuse `Reader` purely as a
// (statement, bind, scan) bundle; nothing requires going through `read_one`.
@(private)
emit_queries_registry :: proc(b: ^strings.Builder, resolved: []Resolved_Query, alias: map[string]string) {
    fmt.sbprintln(b, "Queries :: struct {")

    for q in resolved {
        field := query_field_name(q.def.name)
        params_type := fmt.tprintf("%s_Params", q.def.name)

        if len(q.row) > 0 {
            row_type := resolved_name(alias, fmt.tprintf("%s_Row", q.def.name))
            fmt.sbprintfln(b, "    %s: sqlite.Reader(%s, %s),", field, params_type, row_type)
        } else {
            fmt.sbprintfln(b, "    %s: sqlite.Bind_Mapping(%s),", field, params_type)
        }
    }

    fmt.sbprintln(b, "}")
    fmt.sbprintln(b)
}

// `queries` is an out-parameter, mutated field by field, rather than a named
// return value copied back on success: a caller's own `... or_return` discards
// a named return's value on the error path, which would silently drop whatever
// this already prepared before a later statement failed — exactly the leak that
// bit `store.odin`'s first version of this. Writing through the pointer means
// partial progress survives regardless of how the caller propagates the error.
// `bind_prepare`/`reader_prepare` failing here would mean a generated statement
// no longer matches its generated struct — impossible by construction, so it
// asserts. Only `reader_prepare`'s allocation (the scan side's column table) is
// a real runtime condition, and that alone propagates.
@(private)
emit_queries_init :: proc(b: ^strings.Builder, resolved: []Resolved_Query, alias: map[string]string) {
    fmt.sbprintln(
        b,
        "queries_init :: proc(db: ^sqlite.Conn, queries: ^Queries, allocator := context.allocator) -> sqlite.Error {",
    )

    for q in resolved {
        field := query_field_name(q.def.name)
        params_type := fmt.tprintf("%s_Params", q.def.name)
        fmt.sbprintfln(b, "    %s_stmt := sqlite.prepare(db, QUERY_SQL[.%s]) or_return", field, q.def.name)

        if len(q.row) > 0 {
            row_type := resolved_name(alias, fmt.tprintf("%s_Row", q.def.name))
            fmt.sbprintfln(
                b,
                "    %s_reader, %s_reader_err := sqlite.reader_prepare(%s_stmt, %s, %s, allocator)",
                field,
                field,
                field,
                params_type,
                row_type,
            )
            fmt.sbprintfln(
                b,
                "    assert(%s_reader_err == .None, \"generated statement matches its generated struct\")",
                field,
            )
            fmt.sbprintfln(b, "    queries.%s = %s_reader", field, field)
        } else {
            fmt.sbprintfln(
                b,
                "    %s_bind, %s_bind_err := sqlite.bind_prepare(%s_stmt, %s)",
                field,
                field,
                field,
                params_type,
            )
            fmt.sbprintfln(
                b,
                "    assert(%s_bind_err == .None, \"generated statement matches its generated struct\")",
                field,
            )
            fmt.sbprintfln(b, "    queries.%s = %s_bind", field, field)
        }
    }

    fmt.sbprintln(b, "    return nil")
    fmt.sbprintln(b, "}")
    fmt.sbprintln(b)
}

@(private)
emit_queries_destroy :: proc(b: ^strings.Builder, resolved: []Resolved_Query) {
    fmt.sbprintln(b, "queries_destroy :: proc(queries: ^Queries, allocator := context.allocator) {")

    for q in resolved {
        field := query_field_name(q.def.name)

        if len(q.row) > 0 {
            fmt.sbprintfln(b, "    sqlite.finalize(queries.%s.statement)", field)
            fmt.sbprintfln(b, "    sqlite.reader_destroy(&queries.%s, allocator)", field)
        } else {
            fmt.sbprintfln(b, "    sqlite.finalize(queries.%s.statement)", field)
        }
    }

    fmt.sbprintln(b, "}")
    fmt.sbprintln(b)
}

// `params_in` is copied to a local: Odin refuses `&` on a by-value parameter and
// `bind`/`read_one`/`read_all` all need a pointer to bind from. The wrapper takes
// `^Queries`, not `^Store`, and returns the raw SQLite result — this package has
// no knowledge of a caller's own error type; `store` translates at the call site.
@(private)
emit_query_wrapper :: proc(b: ^strings.Builder, q: Resolved_Query, alias: map[string]string) {
    if q.def.cardinality == .Manual {
        return
    }

    field := query_field_name(q.def.name)
    params_type := fmt.tprintf("%s_Params", q.def.name)

    switch q.def.cardinality {
    case .Exec:
        fmt.sbprintfln(b, "%s :: proc(q: ^Queries, params_in: %s) -> sqlite.Result {{", field, params_type)
        fmt.sbprintln(b, "    params := params_in")
        fmt.sbprintfln(b, "    return sqlite.execute(&q.%s, &params)", field)
        fmt.sbprintln(b, "}")
        fmt.sbprintln(b)

    case .One:
        row_type := resolved_name(alias, fmt.tprintf("%s_Row", q.def.name))
        fmt.sbprintfln(
            b,
            "%s :: proc(q: ^Queries, params_in: %s, allocator := context.allocator) -> (%s, sqlite.Error) {{",
            field,
            params_type,
            row_type,
        )
        fmt.sbprintln(b, "    params := params_in")
        fmt.sbprintfln(b, "    return sqlite.read_one(&q.%s, &params, allocator)", field)
        fmt.sbprintln(b, "}")
        fmt.sbprintln(b)

    case .Many:
        row_type := resolved_name(alias, fmt.tprintf("%s_Row", q.def.name))
        fmt.sbprintfln(
            b,
            "%s :: proc(q: ^Queries, params_in: %s, allocator := context.allocator, cap_hint := 0) -> ([]%s, sqlite.Error) {{",
            field,
            params_type,
            row_type,
        )
        fmt.sbprintln(b, "    params := params_in")
        fmt.sbprintfln(b, "    return sqlite.read_all(&q.%s, &params, allocator, cap_hint)", field)
        fmt.sbprintln(b, "}")
        fmt.sbprintln(b)

    case .Manual:
    }
}

// `snake_case` field/local name for a `Pascal_Case` query name — the registry
// field, the statement-local variable inside `queries_init`, and the generated
// wrapper's function name all share it.
@(private)
query_field_name :: proc(name: string) -> string {
    return strings.to_lower(name, context.temp_allocator)
}
