// Generated by tools/sqlgen. DO NOT EDIT.
const sql = @import("sql");

pub const DeleteProviders = sql.ExecQuery(
    \\DELETE FROM catalog_providers;
,
    struct {},
);

pub const DeleteModels = sql.ExecQuery(
    \\DELETE FROM catalog_models;
,
    struct {},
);

pub const InsertProvider = sql.ExecQuery(
    \\INSERT INTO catalog_providers (id, data) VALUES (:id, :data);
,
    struct {
        id: []const u8,
        data: []const u8,
    },
);

pub const InsertModel = sql.ExecQuery(
    \\INSERT INTO catalog_models (id, provider_id, data) VALUES (:id, :provider_id, :data);
,
    struct {
        id: []const u8,
        provider_id: []const u8,
        data: []const u8,
    },
);

pub const SetEtag = sql.ExecQuery(
    \\INSERT OR REPLACE INTO catalog_meta (k, v) VALUES ('etag', :v);
,
    struct {
        v: []const u8,
    },
);

pub const SelectProviders = sql.ManyQuery(
    \\SELECT data FROM catalog_providers ORDER BY id;
,
    struct {},
    struct {
        data: []const u8,
    },
);

pub const SelectModels = sql.ManyQuery(
    \\SELECT data FROM catalog_models WHERE provider_id = :provider_id ORDER BY id;
,
    struct {
        provider_id: []const u8,
    },
    struct {
        data: []const u8,
    },
);

pub const GetEtag = sql.OptionalQuery(
    \\SELECT v FROM catalog_meta WHERE k = 'etag';
,
    struct {},
    struct {
        v: []const u8,
    },
);

pub const Queries = struct {
    delete_providers: DeleteProviders,
    delete_models: DeleteModels,
    insert_provider: InsertProvider,
    insert_model: InsertModel,
    set_etag: SetEtag,
    select_providers: SelectProviders,
    select_models: SelectModels,
    get_etag: GetEtag,

    pub fn prepareAll(conn: sql.Connection) !@This() {
        return sql.prepareAll(@This(), conn);
    }

    pub fn deinit(self: *@This()) void {
        sql.deinitAll(self);
    }
};
