// Generated by tools/sqlgen. DO NOT EDIT.
const sql = @import("sql");

pub const DeleteProviders = sql.ExecQuery(
    \\DELETE FROM catalog_providers;
,
    struct {},
);

pub const DeleteModels = sql.ExecQuery(
    \\DELETE FROM catalog_models;
,
    struct {},
);

pub const InsertProvider = sql.ExecQuery(
    \\INSERT INTO catalog_providers (id, data) VALUES (:id, :data);
,
    struct {
        id: []const u8,
        data: []const u8,
    },
);

pub const InsertModel = sql.ExecQuery(
    \\INSERT INTO catalog_models (id, provider_id, data) VALUES (:id, :provider_id, :data);
,
    struct {
        id: []const u8,
        provider_id: []const u8,
        data: []const u8,
    },
);

pub const SetEtag = sql.ExecQuery(
    \\INSERT OR REPLACE INTO catalog_meta (k, v) VALUES ('etag', :v);
,
    struct {
        v: []const u8,
    },
);

pub const SelectProviders = sql.ManyQuery(
    \\SELECT data FROM catalog_providers ORDER BY id;
,
    struct {},
    struct {
        data: []const u8,
    },
);

pub const SelectModels = sql.ManyQuery(
    \\SELECT data FROM catalog_models WHERE provider_id = :provider_id ORDER BY id;
,
    struct {
        provider_id: []const u8,
    },
    struct {
        data: []const u8,
    },
);

pub const GetEtag = sql.OptionalQuery(
    \\SELECT v FROM catalog_meta WHERE k = 'etag';
,
    struct {},
    struct {
        v: []const u8,
    },
);

pub const InsertConfig = sql.ExecQuery(
    \\INSERT INTO session_configs(session_id, config_rev, model, reasoning)
    \\    VALUES (:session_id, :config_rev, :model, :reasoning);
,
    struct {
        session_id: [16]u8,
        config_rev: u64,
        model: []const u8,
        reasoning: []const u8,
    },
);

pub const AdvanceConfig = sql.OneQuery(
    \\UPDATE sessions SET
    \\    model           = :model,
    \\    reasoning       = :reasoning,
    \\    config_rev      = :config_rev,
    \\    config_rev_high = MAX(config_rev_high, :config_rev),
    \\    projection_seq  = :seq,
    \\    updated_at_ms   = MAX(updated_at_ms, :updated_at_ms)
    \\WHERE id = :id AND :config_rev >= config_rev_high RETURNING 1 AS advanced;
,
    struct {
        model: []const u8,
        reasoning: []const u8,
        config_rev: u64,
        seq: u64,
        updated_at_ms: u64,
        id: [16]u8,
    },
    struct {
        advanced: i64,
    },
);

pub const ConfigByRevision = sql.OptionalQuery(
    \\SELECT model, reasoning FROM session_configs WHERE session_id = :session_id AND config_rev = :config_rev;
,
    struct {
        session_id: [16]u8,
        config_rev: u64,
    },
    struct {
        model: []const u8,
        reasoning: []const u8,
    },
);

pub const AllocSeq = sql.OneQuery(
    \\UPDATE sessions SET seq_high = seq_high + 1 WHERE id = :id RETURNING seq_high;
,
    struct {
        id: [16]u8,
    },
    struct {
        seq_high: u64,
    },
);

pub const AppendEvent = sql.ExecQuery(
    \\INSERT INTO events(session_id, seq, event_id, committed_at_ms, name, payload)
    \\    VALUES (:session_id, :seq, :event_id, :committed_at_ms, :name, :payload);
,
    struct {
        session_id: [16]u8,
        seq: u64,
        event_id: [16]u8,
        committed_at_ms: u64,
        name: []const u8,
        payload: []const u8,
    },
);

pub const BumpIds = sql.OneQuery(
    \\UPDATE sessions SET
    \\    message_id_high = MAX(message_id_high, :message_id_high),
    \\    run_id_high     = MAX(run_id_high, :run_id_high),
    \\    input_id_high   = MAX(input_id_high, :input_id_high),
    \\    config_rev_high = MAX(config_rev_high, :config_rev_high)
    \\    WHERE id = :id RETURNING 1 AS bumped;
,
    struct {
        message_id_high: u64,
        run_id_high: u64,
        input_id_high: u64,
        config_rev_high: u64,
        id: [16]u8,
    },
    struct {
        bumped: i64,
    },
);

pub const ReadHigh = sql.OptionalQuery(
    \\SELECT seq_high, message_id_high, run_id_high, input_id_high, config_rev_high
    \\    FROM sessions WHERE id = :id;
,
    struct {
        id: [16]u8,
    },
    struct {
        seq_high: u64,
        message_id_high: u64,
        run_id_high: u64,
        input_id_high: u64,
        config_rev_high: u64,
    },
);

pub const AllocRunId = sql.OneQuery(
    \\UPDATE sessions SET run_id_high = run_id_high + 1 WHERE id = :id RETURNING run_id_high;
,
    struct {
        id: [16]u8,
    },
    struct {
        run_id_high: u64,
    },
);

pub const AllocMessageId = sql.OneQuery(
    \\UPDATE sessions SET message_id_high = message_id_high + 1 WHERE id = :id RETURNING message_id_high;
,
    struct {
        id: [16]u8,
    },
    struct {
        message_id_high: u64,
    },
);

pub const AllocInputId = sql.OneQuery(
    \\UPDATE sessions SET input_id_high = input_id_high + 1 WHERE id = :id RETURNING input_id_high;
,
    struct {
        id: [16]u8,
    },
    struct {
        input_id_high: u64,
    },
);

pub const InsertPendingInput = sql.ExecQuery(
    \\INSERT INTO pending_inputs(session_id, input_id, seq, queued_at_ms, payload)
    \\    VALUES (:session_id, :input_id, :seq, :queued_at_ms, :payload);
,
    struct {
        session_id: [16]u8,
        input_id: u64,
        seq: u64,
        queued_at_ms: u64,
        payload: []const u8,
    },
);

pub const PendingInputById = sql.OptionalQuery(
    \\SELECT p.input_id AS row_input_id,
    \\       p.seq,
    \\       p.queued_at_ms,
    \\       p.payload,
    \\       e.name AS event_name
    \\FROM pending_inputs p
    \\JOIN events e ON e.session_id = p.session_id AND e.seq = p.seq
    \\WHERE p.session_id = :session_id AND p.input_id = :input_id;
,
    struct {
        session_id: [16]u8,
        input_id: u64,
    },
    struct {
        row_input_id: u64,
        seq: u64,
        queued_at_ms: u64,
        payload: []const u8,
        event_name: []const u8,
    },
);

pub const PendingInputs = sql.ManyQuery(
    \\SELECT p.input_id AS row_input_id,
    \\       p.seq,
    \\       p.queued_at_ms,
    \\       p.payload,
    \\       e.name AS event_name
    \\FROM pending_inputs p
    \\JOIN events e ON e.session_id = p.session_id AND e.seq = p.seq
    \\WHERE p.session_id = :session_id
    \\ORDER BY p.seq ASC;
,
    struct {
        session_id: [16]u8,
    },
    struct {
        row_input_id: u64,
        seq: u64,
        queued_at_ms: u64,
        payload: []const u8,
        event_name: []const u8,
    },
);

pub const DeletePendingInput = sql.OneQuery(
    \\DELETE FROM pending_inputs
    \\WHERE session_id = :session_id AND input_id = :input_id
    \\RETURNING 1 AS deleted;
,
    struct {
        session_id: [16]u8,
        input_id: u64,
    },
    struct {
        deleted: i64,
    },
);

pub const PendingSessionIds = sql.ManyQuery(
    \\SELECT DISTINCT session_id
    \\FROM pending_inputs
    \\ORDER BY session_id;
,
    struct {},
    struct {
        session_id: [16]u8,
    },
);

pub const InsertMessage = sql.ExecQuery(
    \\INSERT INTO messages(
    \\    session_id, message_id, seq, role, run_id, config_rev, model, protocol, finish,
    \\    tokens_input, tokens_output, tokens_reasoning, tokens_cache_read, tokens_cache_write, cost, created_at_ms
    \\) VALUES (
    \\    :session_id, :message_id, :seq, :role, :run_id, :config_rev, :model, :protocol, :finish,
    \\    :tokens_input, :tokens_output, :tokens_reasoning, :tokens_cache_read, :tokens_cache_write, :cost, :created_at_ms
    \\);
,
    struct {
        session_id: [16]u8,
        message_id: u64,
        seq: u64,
        role: []const u8,
        run_id: ?u64,
        config_rev: ?u64,
        model: ?[]const u8,
        protocol: ?[]const u8,
        finish: ?[]const u8,
        tokens_input: ?u64,
        tokens_output: ?u64,
        tokens_reasoning: ?u64,
        tokens_cache_read: ?u64,
        tokens_cache_write: ?u64,
        cost: ?f64,
        created_at_ms: u64,
    },
);

pub const AdvanceMessage = sql.OneQuery(
    \\UPDATE sessions SET
    \\    message_count           = message_count + 1,
    \\    message_id_high         = MAX(message_id_high, :message_id),
    \\    usage_input_total       = usage_input_total       + :add_input,
    \\    usage_output_total      = usage_output_total      + :add_output,
    \\    usage_reasoning_total   = usage_reasoning_total    + :add_reasoning,
    \\    usage_cache_read_total  = usage_cache_read_total   + :add_cache_read,
    \\    usage_cache_write_total = usage_cache_write_total  + :add_cache_write,
    \\    projection_seq          = :seq,
    \\    updated_at_ms           = MAX(updated_at_ms, :updated_at_ms)
    \\WHERE id = :id RETURNING 1 AS advanced;
,
    struct {
        message_id: u64,
        add_input: u64,
        add_output: u64,
        add_reasoning: u64,
        add_cache_read: u64,
        add_cache_write: u64,
        seq: u64,
        updated_at_ms: u64,
        id: [16]u8,
    },
    struct {
        advanced: i64,
    },
);

pub const MessagePage = sql.ManyQuery(
    \\SELECT m.message_id AS message_id, e.payload AS payload
    \\FROM messages m JOIN events e ON e.session_id = m.session_id AND e.seq = m.seq
    \\WHERE m.session_id = :session_id AND m.message_id < :cursor_message_id
    \\ORDER BY m.message_id DESC
    \\LIMIT :limit;
,
    struct {
        session_id: [16]u8,
        cursor_message_id: u64,
        limit: i64,
    },
    struct {
        message_id: u64,
        payload: []const u8,
    },
);

pub const InsertSession = sql.ExecQuery(
    \\INSERT INTO sessions(
    \\    id, workspace_id, origin, parent_id, parent_message_id, parent_part_id, source_id,
    \\    profile, model, reasoning, config_rev, permission, max_rounds, title, agent,
    \\    created_by_name, created_by_version, created_at_ms, updated_at_ms
    \\) VALUES (
    \\    :id, :workspace_id, :origin, :parent_id, :parent_message_id, :parent_part_id, :source_id,
    \\    :profile, :model, :reasoning, :config_rev, :permission, :max_rounds, :title, :agent,
    \\    :created_by_name, :created_by_version, :created_at_ms, :updated_at_ms
    \\);
,
    struct {
        id: [16]u8,
        workspace_id: [16]u8,
        origin: []const u8,
        parent_id: ?[16]u8,
        parent_message_id: ?u64,
        parent_part_id: ?u64,
        source_id: ?[16]u8,
        profile: []const u8,
        model: []const u8,
        reasoning: []const u8,
        config_rev: u64,
        permission: []const u8,
        max_rounds: ?u64,
        title: []const u8,
        agent: ?[]const u8,
        created_by_name: ?[]const u8,
        created_by_version: ?[]const u8,
        created_at_ms: u64,
        updated_at_ms: u64,
    },
);

pub const SessionExists = sql.OptionalQuery(
    \\SELECT 1 AS present FROM sessions WHERE id = :id;
,
    struct {
        id: [16]u8,
    },
    struct {
        present: i64,
    },
);

pub const SessionSnapshot = sql.OptionalQuery(
    \\SELECT
    \\    id, workspace_id,
    \\    origin, parent_id, parent_message_id, parent_part_id, source_id,
    \\    profile, model, reasoning, config_rev, permission, max_rounds, title, agent,
    \\    created_by_name, created_by_version,
    \\    message_count,
    \\    usage_input_total, usage_output_total, usage_reasoning_total, usage_cache_read_total, usage_cache_write_total,
    \\    created_at_ms, updated_at_ms,
    \\    open_run_id, open_run_kind, open_run_started_at_ms
    \\FROM sessions
    \\WHERE id = :id;
,
    struct {
        id: [16]u8,
    },
    struct {
        id: [16]u8,
        workspace_id: [16]u8,
        origin: []const u8,
        parent_id: ?[16]u8,
        parent_message_id: ?u64,
        parent_part_id: ?u64,
        source_id: ?[16]u8,
        profile: []const u8,
        model: []const u8,
        reasoning: []const u8,
        config_rev: u64,
        permission: []const u8,
        max_rounds: ?u64,
        title: []const u8,
        agent: ?[]const u8,
        created_by_name: ?[]const u8,
        created_by_version: ?[]const u8,
        message_count: u64,
        usage_input_total: u64,
        usage_output_total: u64,
        usage_reasoning_total: u64,
        usage_cache_read_total: u64,
        usage_cache_write_total: u64,
        created_at_ms: u64,
        updated_at_ms: u64,
        open_run_id: ?u64,
        open_run_kind: ?[]const u8,
        open_run_started_at_ms: ?u64,
    },
);

pub const SetOpenRun = sql.OneQuery(
    \\UPDATE sessions SET
    \\    open_run_id = :run_id,
    \\    open_run_kind = :kind,
    \\    open_run_started_at_ms = :started_at_ms
    \\WHERE id = :id AND open_run_id IS NULL
    \\RETURNING 1 AS changed;
,
    struct {
        run_id: u64,
        kind: []const u8,
        started_at_ms: u64,
        id: [16]u8,
    },
    struct {
        changed: i64,
    },
);

pub const ClearOpenRun = sql.OneQuery(
    \\UPDATE sessions SET
    \\    open_run_id = NULL,
    \\    open_run_kind = NULL,
    \\    open_run_started_at_ms = NULL
    \\WHERE id = :id
    \\  AND open_run_id = :run_id
    \\  AND open_run_kind = :kind
    \\  AND open_run_started_at_ms = :started_at_ms
    \\RETURNING 1 AS changed;
,
    struct {
        id: [16]u8,
        run_id: u64,
        kind: []const u8,
        started_at_ms: u64,
    },
    struct {
        changed: i64,
    },
);

pub const SelectOpenRuns = sql.ManyQuery(
    \\SELECT
    \\    id,
    \\    open_run_id AS run_id,
    \\    open_run_kind AS kind,
    \\    open_run_started_at_ms AS started_at_ms
    \\FROM sessions
    \\WHERE open_run_id IS NOT NULL
    \\ORDER BY id;
,
    struct {},
    struct {
        id: [16]u8,
        run_id: u64,
        kind: []const u8,
        started_at_ms: u64,
    },
);

pub const SessionPageRecent = sql.ManyQuery(
    \\SELECT
    \\    id, workspace_id,
    \\    origin, parent_id, parent_message_id, parent_part_id, source_id,
    \\    profile, model, reasoning, config_rev, permission, max_rounds, title, agent,
    \\    created_by_name, created_by_version,
    \\    message_count,
    \\    usage_input_total, usage_output_total, usage_reasoning_total, usage_cache_read_total, usage_cache_write_total,
    \\    created_at_ms, updated_at_ms
    \\FROM sessions
    \\WHERE (NOT :top_level OR origin IN ('root', 'fork'))
    \\  AND (updated_at_ms, id) < (:cursor_updated_at_ms, :cursor_id)
    \\ORDER BY updated_at_ms DESC, id DESC
    \\LIMIT :limit;
,
    struct {
        top_level: bool,
        cursor_updated_at_ms: u64,
        cursor_id: [16]u8,
        limit: i64,
    },
    struct {
        id: [16]u8,
        workspace_id: [16]u8,
        origin: []const u8,
        parent_id: ?[16]u8,
        parent_message_id: ?u64,
        parent_part_id: ?u64,
        source_id: ?[16]u8,
        profile: []const u8,
        model: []const u8,
        reasoning: []const u8,
        config_rev: u64,
        permission: []const u8,
        max_rounds: ?u64,
        title: []const u8,
        agent: ?[]const u8,
        created_by_name: ?[]const u8,
        created_by_version: ?[]const u8,
        message_count: u64,
        usage_input_total: u64,
        usage_output_total: u64,
        usage_reasoning_total: u64,
        usage_cache_read_total: u64,
        usage_cache_write_total: u64,
        created_at_ms: u64,
        updated_at_ms: u64,
    },
);

pub const SessionPageWorkspace = sql.ManyQuery(
    \\SELECT
    \\    id, workspace_id,
    \\    origin, parent_id, parent_message_id, parent_part_id, source_id,
    \\    profile, model, reasoning, config_rev, permission, max_rounds, title, agent,
    \\    created_by_name, created_by_version,
    \\    message_count,
    \\    usage_input_total, usage_output_total, usage_reasoning_total, usage_cache_read_total, usage_cache_write_total,
    \\    created_at_ms, updated_at_ms
    \\FROM sessions
    \\WHERE workspace_id = :filter_workspace_id
    \\  AND (NOT :top_level OR origin IN ('root', 'fork'))
    \\  AND (updated_at_ms, id) < (:cursor_updated_at_ms, :cursor_id)
    \\ORDER BY updated_at_ms DESC, id DESC
    \\LIMIT :limit;
,
    struct {
        filter_workspace_id: [16]u8,
        top_level: bool,
        cursor_updated_at_ms: u64,
        cursor_id: [16]u8,
        limit: i64,
    },
    struct {
        id: [16]u8,
        workspace_id: [16]u8,
        origin: []const u8,
        parent_id: ?[16]u8,
        parent_message_id: ?u64,
        parent_part_id: ?u64,
        source_id: ?[16]u8,
        profile: []const u8,
        model: []const u8,
        reasoning: []const u8,
        config_rev: u64,
        permission: []const u8,
        max_rounds: ?u64,
        title: []const u8,
        agent: ?[]const u8,
        created_by_name: ?[]const u8,
        created_by_version: ?[]const u8,
        message_count: u64,
        usage_input_total: u64,
        usage_output_total: u64,
        usage_reasoning_total: u64,
        usage_cache_read_total: u64,
        usage_cache_write_total: u64,
        created_at_ms: u64,
        updated_at_ms: u64,
    },
);

pub const SessionPageParent = sql.ManyQuery(
    \\SELECT
    \\    id, workspace_id,
    \\    origin, parent_id, parent_message_id, parent_part_id, source_id,
    \\    profile, model, reasoning, config_rev, permission, max_rounds, title, agent,
    \\    created_by_name, created_by_version,
    \\    message_count,
    \\    usage_input_total, usage_output_total, usage_reasoning_total, usage_cache_read_total, usage_cache_write_total,
    \\    created_at_ms, updated_at_ms
    \\FROM sessions
    \\WHERE parent_id = :filter_parent_id
    \\  AND (:filter_workspace_id IS NULL OR workspace_id = :filter_workspace_id)
    \\  AND (NOT :top_level OR origin IN ('root', 'fork'))
    \\  AND (updated_at_ms, id) < (:cursor_updated_at_ms, :cursor_id)
    \\ORDER BY updated_at_ms DESC, id DESC
    \\LIMIT :limit;
,
    struct {
        filter_parent_id: [16]u8,
        filter_workspace_id: ?[16]u8,
        top_level: bool,
        cursor_updated_at_ms: u64,
        cursor_id: [16]u8,
        limit: i64,
    },
    struct {
        id: [16]u8,
        workspace_id: [16]u8,
        origin: []const u8,
        parent_id: ?[16]u8,
        parent_message_id: ?u64,
        parent_part_id: ?u64,
        source_id: ?[16]u8,
        profile: []const u8,
        model: []const u8,
        reasoning: []const u8,
        config_rev: u64,
        permission: []const u8,
        max_rounds: ?u64,
        title: []const u8,
        agent: ?[]const u8,
        created_by_name: ?[]const u8,
        created_by_version: ?[]const u8,
        message_count: u64,
        usage_input_total: u64,
        usage_output_total: u64,
        usage_reasoning_total: u64,
        usage_cache_read_total: u64,
        usage_cache_write_total: u64,
        created_at_ms: u64,
        updated_at_ms: u64,
    },
);

pub const SessionCountRecent = sql.OneQuery(
    \\SELECT count(*) AS total FROM sessions
    \\WHERE (NOT :top_level OR origin IN ('root', 'fork'));
,
    struct {
        top_level: bool,
    },
    struct {
        total: u64,
    },
);

pub const SessionCountWorkspace = sql.OneQuery(
    \\SELECT count(*) AS total FROM sessions
    \\WHERE workspace_id = :filter_workspace_id
    \\  AND (NOT :top_level OR origin IN ('root', 'fork'));
,
    struct {
        filter_workspace_id: [16]u8,
        top_level: bool,
    },
    struct {
        total: u64,
    },
);

pub const SessionCountParent = sql.OneQuery(
    \\SELECT count(*) AS total FROM sessions
    \\WHERE parent_id = :filter_parent_id
    \\  AND (:filter_workspace_id IS NULL OR workspace_id = :filter_workspace_id)
    \\  AND (NOT :top_level OR origin IN ('root', 'fork'));
,
    struct {
        filter_parent_id: [16]u8,
        filter_workspace_id: ?[16]u8,
        top_level: bool,
    },
    struct {
        total: u64,
    },
);

pub const InsertPrompt = sql.ExecQuery(
    \\INSERT INTO session_prompts(session_id, prompt) VALUES (:session_id, :prompt);
,
    struct {
        session_id: [16]u8,
        prompt: []const u8,
    },
);

pub const SelectPrompt = sql.OptionalQuery(
    \\SELECT prompt FROM session_prompts WHERE session_id = :session_id;
,
    struct {
        session_id: [16]u8,
    },
    struct {
        prompt: []const u8,
    },
);

pub const WorkspaceByStableKey = sql.OptionalQuery(
    \\SELECT id FROM workspaces WHERE kind = :kind AND stable_key = :stable_key;
,
    struct {
        kind: []const u8,
        stable_key: []const u8,
    },
    struct {
        id: [16]u8,
    },
);

pub const InsertWorkspace = sql.ExecQuery(
    \\INSERT INTO workspaces(id, kind, root, title, stable_key)
    \\    VALUES (:id, :kind, :root, :title, :stable_key);
,
    struct {
        id: [16]u8,
        kind: []const u8,
        root: []const u8,
        title: []const u8,
        stable_key: ?[]const u8,
    },
);

pub const WorkspaceById = sql.OptionalQuery(
    \\SELECT id, kind, root, title FROM workspaces WHERE id = :id;
,
    struct {
        id: [16]u8,
    },
    struct {
        id: [16]u8,
        kind: []const u8,
        root: []const u8,
        title: []const u8,
    },
);

pub const WorkspaceList = sql.ManyQuery(
    \\SELECT id, kind, root, title FROM workspaces ORDER BY title, id;
,
    struct {},
    struct {
        id: [16]u8,
        kind: []const u8,
        root: []const u8,
        title: []const u8,
    },
);

pub const Queries = struct {
    delete_providers: DeleteProviders,
    delete_models: DeleteModels,
    insert_provider: InsertProvider,
    insert_model: InsertModel,
    set_etag: SetEtag,
    select_providers: SelectProviders,
    select_models: SelectModels,
    get_etag: GetEtag,
    insert_config: InsertConfig,
    advance_config: AdvanceConfig,
    config_by_revision: ConfigByRevision,
    alloc_seq: AllocSeq,
    append_event: AppendEvent,
    bump_ids: BumpIds,
    read_high: ReadHigh,
    alloc_run_id: AllocRunId,
    alloc_message_id: AllocMessageId,
    alloc_input_id: AllocInputId,
    insert_pending_input: InsertPendingInput,
    pending_input_by_id: PendingInputById,
    pending_inputs: PendingInputs,
    delete_pending_input: DeletePendingInput,
    pending_session_ids: PendingSessionIds,
    insert_message: InsertMessage,
    advance_message: AdvanceMessage,
    message_page: MessagePage,
    insert_session: InsertSession,
    session_exists: SessionExists,
    session_snapshot: SessionSnapshot,
    set_open_run: SetOpenRun,
    clear_open_run: ClearOpenRun,
    select_open_runs: SelectOpenRuns,
    session_page_recent: SessionPageRecent,
    session_page_workspace: SessionPageWorkspace,
    session_page_parent: SessionPageParent,
    session_count_recent: SessionCountRecent,
    session_count_workspace: SessionCountWorkspace,
    session_count_parent: SessionCountParent,
    insert_prompt: InsertPrompt,
    select_prompt: SelectPrompt,
    workspace_by_stable_key: WorkspaceByStableKey,
    insert_workspace: InsertWorkspace,
    workspace_by_id: WorkspaceById,
    workspace_list: WorkspaceList,

    pub fn prepareAll(conn: sql.Connection) !@This() {
        return sql.prepareAll(@This(), conn);
    }

    pub fn deinit(self: *@This()) void {
        sql.deinitAll(self);
    }
};
