import { equal } from "yuke:test";
import { plugins as viaFacade } from "yuke";
import { plugins as viaExt } from "yuke:ext";
equal(viaFacade, viaExt);
import { composerVim, agents } from "yuke/plugins";
import { composerVim as internalVim } from "yuke:composer-vim";
import { agents as internalAgents } from "yuke:agents";
import * as chat from "yuke/chat";
equal(composerVim, internalVim);
equal(agents, internalAgents);
for (const name of ["composerVim", "composerMode", "setComposerMode", "transcriptVim", "agents"]) equal(Object.hasOwn(chat, name), false);
