import { equal } from "yuke:internal/test";
import { plugins as viaFacade } from "yuke";
import { plugins as viaExt } from "yuke:internal/ext";
import { composerVim, agents } from "yuke:plugins";
import { composerVim as internalVim } from "yuke:internal/composer-vim";
import { agents as internalAgents } from "yuke:internal/agents";
import * as chat from "yuke:chat";
equal(viaFacade, viaExt);
equal(composerVim, internalVim);
equal(agents, internalAgents);
for (const name of ["composerVim", "composerMode", "setComposerMode", "transcriptVim", "agents"]) equal(Object.hasOwn(chat, name), false);
