// Bundle the plugin API into two declaration files: `yuke-modules.d.ts` names the public modules, and `yuke.d.ts` fills them.
// `yuke.d.ts` is a module, so its internal modules are private namespaces that plugin code cannot import.
// usage: node tools/typesgen/main.ts <tsc-declaration-dir> <output-dir>
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { posix } from "node:path";

const [emitted, output] = process.argv.slice(2);
if (!emitted || !output) throw new Error("usage: main.ts <tsc-declaration-dir> <output-dir>");
const app = "src/js/app";
// This script declares the globals of every host; the other scripts stay private to the bundle.
const globals = "globals.d.ts";

const list = (dir: string) => readdirSync(dir).filter((name) => name.endsWith(".d.ts")).sort();

// A `$` prefix keeps a namespace apart from the members it exports, such as `$ui.ui`.
const space = (path: string) => "$" + path.replace(/[^A-Za-z0-9]/g, "_");

const internal = "yuke:internal/";

// A specifier is `yuke:internal/<path>` or a path relative to `base`, the file's directory under the app.
function target(spec: string, base: string): string {
  if (spec.startsWith(internal)) return space(spec.slice(internal.length));
  if (spec.startsWith(".")) return space(posix.normalize(posix.join(base, spec.replace(/\.js$/, ""))));
  throw new Error(`unknown specifier ${spec}`);
}

// A namespace has no import or export statements, so each named binding becomes an alias.
function aliases(indent: string, lead: string, names: string, ns: string): string {
  return names.split(",").map((name) => name.trim().replace(/^type /, "")).filter(Boolean).map((name) => {
    const [from, as = from] = name.split(/\s+as\s+/);
    return `${indent}${lead}import ${as} = ${ns}.${from};`;
  }).join("\n");
}

function rewrite(text: string, base: string): string {
  const out = text
    .replace(/^([ \t]*)(export )?import (?:type )?\{([^}]*)\} from "([^"]+)";/gm, (_all, indent: string, lead = "", names: string, spec: string) => aliases(indent, lead, names, target(spec, base)))
    .replace(/^([ \t]*)export (?:type )?\{([^}]*)\} from "([^"]+)";/gm, (_all, indent: string, names: string, spec: string) => aliases(indent, "export ", names, target(spec, base)))
    .replace(/^([ \t]*)(?:import|(export)) \* as (\w+) from "([^"]+)";/gm, (_all, indent: string, lead: string | undefined, name: string, spec: string) => `${indent}${lead ? "export " : ""}import ${name} = ${target(spec, base)};`)
    .replace(/import\("([^"]+)"\)/g, (_all, spec: string) => target(spec, base))
    .replace(/^export \{\};\n/gm, "")
    // tsc repeats each JSDoc import and typedef after the declaration it emits.
    .replace(/^[ \t]*\/\*\* @(?:import|typedef) .*\*\/\n/gm, "")
    .replace(/^export declare /gm, "export ")
    .replace(/^declare /gm, "");
  const left = /^.*(?: from "|export \*|export \{|export default|export =).*$/m.exec(out);
  if (left) throw new Error(`no namespace form for: ${left[0]}`);
  return out.trimEnd();
}

// The header uses the package version, not the nightly version, so a nightly build does not change the committed header.
const version = /^\s*\.version\s*=\s*"([^"]+)"/m.exec(readFileSync("build.zig.zon", "utf8"))?.[1];
if (!version) throw new Error("build.zig.zon has no .version");
const header = ["// Generated by yuke. Do not edit.", `// version: ${version}`, ""];
const modules = [...header];
// A chunk is a root, which always stays, or an internal namespace, which keeps only the declarations the roots reach.
type Chunk = { text: string } | { space: string; head: string; body: string };
const chunks: Chunk[] = [{ text: [...header, "export {};", ""].join("\n") }];
const block = (open: string, body: string) => chunks.push({ text: `${open} {\n${body}\n}\n` });
const internalBlock = (space: string, body: string, lead = "") => chunks.push({ space, head: `${lead}declare namespace ${space}`, body });
// `public/yuke.js` is `yuke` and `public/<name>.js` is `yuke:<name>`.
for (const name of list(`${emitted}/public`)) {
  const stem = name.slice(0, -".d.ts".length);
  const pub = stem === "yuke" ? "yuke" : `yuke:${stem}`;
  modules.push(`declare module "${pub}" { export {}; }`);
  block(`declare module "${pub}"`, rewrite(readFileSync(`${emitted}/public/${name}`, "utf8"), "public"));
}
for (const name of list(emitted)) {
  const stem = name.slice(0, -".d.ts".length);
  internalBlock(space(stem), rewrite(readFileSync(`${emitted}/${name}`, "utf8"), "."));
}
for (const name of list(`${app}/types/native`)) {
  const text = readFileSync(`${app}/types/native/${name}`, "utf8");
  const native = /^declare module "yuke:internal\/(native\/[^"]+)" \{\n([^]*)\n\}\n?$/m.exec(text);
  if (!native) throw new Error(`${name}: a native module must be the whole file`);
  // The split reads declarations at column 0, so the loader removes the one indent of a module body.
  internalBlock(space(native[1]), rewrite(native[2].replace(/^  /gm, ""), "types/native"), text.slice(0, native.index));
}
for (const name of list(`${app}/types`)) {
  const text = readFileSync(`${app}/types/${name}`, "utf8");
  const own = space("types/" + name.slice(0, -".d.ts".length));
  if (/^(import|export) /m.test(text)) internalBlock(own, rewrite(text, "types"));
  else if (name === globals) block("declare global", rewrite(text, "types"));
  else chunks.push({ text: text.trimEnd() + "\n" });
}
chunks.push({ text: readFileSync(`${app}/generated/proto.d.ts`, "utf8").trimEnd() + "\n" });

// TypeScript merges an augmentation only into an interface, so a plugin can add to these through `declare module "yuke"`.
// `yuke` declares each one as an interface over its base, and its home namespace reads the merged interface back.
const open = ["Events"];
const root = chunks.find((chunk) => "text" in chunk && chunk.text.startsWith('declare module "yuke" {'));
if (!root || !("text" in root)) throw new Error("no yuke module");
for (const name of open) {
  const alias = new RegExp(`^export type ${name} = (\\$\\w+)\\.${name};$`, "m").exec(root.text);
  if (!alias) throw new Error(`yuke does not export ${name}`);
  const home = chunks.find((chunk) => "space" in chunk && chunk.space === alias[1]);
  const own = new RegExp(`^export interface ${name}\\b`, "m");
  if (!home || !("body" in home) || !own.test(home.body)) throw new Error(`${alias[1]} does not declare interface ${name}`);
  root.text = root.text.replace(alias[0], `export interface ${name} extends ${alias[1]}.${name}Base {}`);
  home.body = home.body.replace(own, `export type ${name} = import("yuke").${name};\nexport interface ${name}Base`);
}

// A declaration starts at column 0 with its keyword. An indented or closing line continues the declaration above it.
const declStart = /^(?:export )?(?:import|abstract class|class|interface|type|const|let|var|function|enum|namespace) ([\w$]+)/;
// A doc comment starts at column 0 and joins the declaration under it.
const commentLine = /^(?:\/\*|\/\/| \*|\s*$)/;
// `import * as X` becomes this alias of a whole namespace. A use of `X.Name` keeps only that member.
const namespaceAlias = /^(?:export )?import ([\w$]+) = (\$\w+);$/;

// Split a namespace body into its declarations. Overloads and merged declarations share one name.
function declarations(space: string, body: string): Map<string, string[]> {
  const byName = new Map<string, string[]>();
  let lines: string[] = [];
  let name: string | undefined;
  const flush = () => {
    if (name === undefined) {
      const stray = lines.find((line) => !commentLine.test(line));
      if (stray !== undefined) throw new Error(`${space}: no declaration form for "${stray}"`);
    } else {
      byName.set(name, [...(byName.get(name) ?? []), lines.join("\n")]);
    }
    lines = [];
    name = undefined;
  };
  for (const line of body.split("\n")) {
    const decl = declStart.exec(line);
    if (decl || line.startsWith("/*") || line.startsWith("//")) {
      // A comment that follows a comment stays in the same piece until a declaration names it.
      if (name !== undefined) flush();
      if (decl) name = decl[1];
    }
    lines.push(line);
  }
  flush();
  return byName;
}

// tsc emits every file that the entries import at runtime. Only the declarations that the roots name belong in the API.
const spaces = new Map<string, Map<string, string[]>>();
const namespaceAliases = new Map<string, Map<string, string>>();
for (const chunk of chunks) {
  if (!("space" in chunk)) continue;
  const byName = declarations(chunk.space, chunk.body);
  spaces.set(chunk.space, byName);
  const own = new Map<string, string>();
  for (const [name, texts] of byName) {
    const alias = namespaceAlias.exec(texts[0]!.split("\n").at(-1)!);
    if (!alias) continue;
    // `keep` does not scan an alias, so a declaration merged with it would lose its references.
    if (texts.length > 1) throw new Error(`${chunk.space}: the alias "${name}" shares its name with another declaration`);
    own.set(name, alias[2]!);
  }
  namespaceAliases.set(chunk.space, own);
}
const kept = new Map<string, Set<string>>();
// Comments and quoted strings name nothing. Template text names nothing, but each `${...}` part is a type.
const inert = /\/\*[^]*?\*\/|\/\/.*|"(?:[^"\\\n]|\\.)*"|'(?:[^'\\\n]|\\.)*'|`(?:[^`\\]|\\.)*`/g;
const blank = (match: string): string => match.startsWith("`") ? " " + [...match.matchAll(/\$\{([^}]*)\}/g)].map((part) => part[1]!.replace(inert, blank)).join(" ") + " " : " ";
// An identifier before `:`, `?:`, or `(` declares a member, so it names nothing.
const localRef = /(?<![\w$.])([A-Za-z_][\w$]*)(?:\.([\w$]+))?(?![\w$]|\??[:(])/g;

function keep(space: string, name: string): void {
  const texts = spaces.get(space)?.get(name);
  const names = kept.get(space) ?? kept.set(space, new Set()).get(space)!;
  if (texts === undefined || names.has(name)) return;
  names.add(name);
  // An alias line names its whole namespace, but only the members that a use names belong in the API.
  if (namespaceAliases.get(space)!.has(name)) return;
  for (const text of texts) reach(text, space);
}
function keepAll(space: string): void {
  for (const name of spaces.get(space)!.keys()) keep(space, name);
}
// Keep `name` of `space`. A namespace alias also keeps `member` of its namespace, or the whole namespace without one.
function use(space: string, name: string, member: string | undefined): void {
  keep(space, name);
  const target = namespaceAliases.get(space)?.get(name);
  if (target === undefined || !spaces.has(target)) return;
  if (member === undefined) keepAll(target);
  else keep(target, member);
}
// Keep each declaration that `text` names. A name can be `$space.Name`, a whole `$space`, or a sibling in `home`.
function reach(text: string, home?: string): void {
  const code = text.replace(inert, blank);
  for (const [, space, name, member] of code.matchAll(/(?<![\w$])(\$\w+)(?:\.([\w$]+)(?:\.([\w$]+))?)?/g)) {
    if (!spaces.has(space!)) continue;
    if (name === undefined) keepAll(space!);
    else use(space!, name, member);
  }
  if (home !== undefined) for (const [, name, member] of code.matchAll(localRef)) use(home, name!, member);
}
for (const chunk of chunks) if ("text" in chunk) reach(chunk.text);

const out: string[] = [];
for (const chunk of chunks) {
  if ("text" in chunk) {
    out.push(chunk.text);
    continue;
  }
  const names = kept.get(chunk.space);
  if (names === undefined || names.size === 0) continue;
  const body = [...spaces.get(chunk.space)!].filter(([name]) => names.has(name)).flatMap(([, texts]) => texts);
  out.push(`${chunk.head} {\n${body.join("\n")}\n}\n`);
}
writeFileSync(posix.join(output, "yuke.d.ts"), out.join("\n"));
writeFileSync(posix.join(output, "yuke-modules.d.ts"), modules.concat("").join("\n"));
