// Bundle the plugin API into two declaration files: `yuke-modules.d.ts` names the four public modules, and `yuke.d.ts` fills them.
// `yuke.d.ts` is a module, so its internal modules are private namespaces that plugin code cannot import.
// usage: node tools/typesgen/main.ts <tsc-declaration-dir> <output-dir>
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { posix } from "node:path";

const [emitted, output] = process.argv.slice(2);
if (!emitted || !output) throw new Error("usage: main.ts <tsc-declaration-dir> <output-dir>");
const app = "src/js/app";
// This script declares the globals of every host; the other scripts stay private to the bundle.
const globals = "globals.d.ts";

const list = (dir: string) => readdirSync(dir).filter((name) => name.endsWith(".d.ts")).sort();

// A `$` prefix keeps a namespace apart from the members it exports, such as `$ui.ui`.
const space = (path: string) => "$" + path.replace(/[^A-Za-z0-9]/g, "_");

const internal = "yuke:internal/";

// A specifier is `yuke:internal/<path>` or a path relative to `base`, the file's directory under the app.
function target(spec: string, base: string): string {
  if (spec.startsWith(internal)) return space(spec.slice(internal.length));
  if (spec.startsWith(".")) return space(posix.normalize(posix.join(base, spec.replace(/\.js$/, ""))));
  throw new Error(`unknown specifier ${spec}`);
}

// A namespace has no import or export statements, so each named binding becomes an alias.
function aliases(indent: string, lead: string, names: string, ns: string): string {
  return names.split(",").map((name) => name.trim().replace(/^type /, "")).filter(Boolean).map((name) => {
    const [from, as = from] = name.split(/\s+as\s+/);
    return `${indent}${lead}import ${as} = ${ns}.${from};`;
  }).join("\n");
}

function rewrite(text: string, base: string): string {
  const out = text
    .replace(/^([ \t]*)(export )?import (?:type )?\{([^}]*)\} from "([^"]+)";/gm, (_all, indent: string, lead = "", names: string, spec: string) => aliases(indent, lead, names, target(spec, base)))
    .replace(/^([ \t]*)export (?:type )?\{([^}]*)\} from "([^"]+)";/gm, (_all, indent: string, names: string, spec: string) => aliases(indent, "export ", names, target(spec, base)))
    .replace(/^([ \t]*)(?:import|(export)) \* as (\w+) from "([^"]+)";/gm, (_all, indent: string, lead: string | undefined, name: string, spec: string) => `${indent}${lead ? "export " : ""}import ${name} = ${target(spec, base)};`)
    .replace(/import\("([^"]+)"\)/g, (_all, spec: string) => target(spec, base))
    .replace(/^export \{\};\n/gm, "")
    // tsc repeats each JSDoc import and typedef after the declaration it emits.
    .replace(/^[ \t]*\/\*\* @(?:import|typedef) .*\*\/\n/gm, "")
    .replace(/^export declare /gm, "export ")
    .replace(/^declare /gm, "");
  const left = /^.*(?: from "|export \*|export \{|export default|export =).*$/m.exec(out);
  if (left) throw new Error(`no namespace form for: ${left[0]}`);
  return out.trimEnd();
}

const header = ["// GENERATED by tools/typesgen (mise run types). Do not edit.", '// The yuke plugin API: "yuke", "yuke:ui", "yuke:chat", and "yuke:plugins".', ""];
const modules = [...header];
// A chunk with a `space` is an internal namespace; it stays only when the public API reaches it.
const chunks: { space?: string; text: string }[] = [{ text: [...header, "export {};", ""].join("\n") }];
const block = (open: string, body: string, space?: string, lead = "") => chunks.push({ space, text: `${lead}${open} {\n${body}\n}\n` });
// `public/yuke.js` is `yuke` and `public/<name>.js` is `yuke:<name>`.
for (const name of list(`${emitted}/public`)) {
  const stem = name.slice(0, -".d.ts".length);
  const pub = stem === "yuke" ? "yuke" : `yuke:${stem}`;
  modules.push(`declare module "${pub}" { export {}; }`);
  block(`declare module "${pub}"`, rewrite(readFileSync(`${emitted}/public/${name}`, "utf8"), "public"));
}
for (const name of list(emitted)) {
  const stem = name.slice(0, -".d.ts".length);
  block(`declare namespace ${space(stem)}`, rewrite(readFileSync(`${emitted}/${name}`, "utf8"), "."), space(stem));
}
for (const name of list(`${app}/types/native`)) {
  const text = readFileSync(`${app}/types/native/${name}`, "utf8");
  const native = /^declare module "yuke:internal\/(native\/[^"]+)" \{\n([^]*)\n\}\n?$/m.exec(text);
  if (!native) throw new Error(`${name}: a native module must be the whole file`);
  block(`declare namespace ${space(native[1])}`, rewrite(native[2], "types/native"), space(native[1]), text.slice(0, native.index));
}
for (const name of list(`${app}/types`)) {
  const text = readFileSync(`${app}/types/${name}`, "utf8");
  const own = space("types/" + name.slice(0, -".d.ts".length));
  if (/^(import|export) /m.test(text)) block(`declare namespace ${own}`, rewrite(text, "types"), own);
  else if (name === globals) block("declare global", rewrite(text, "types"));
  else chunks.push({ text: text.trimEnd() + "\n" });
}
chunks.push({ text: readFileSync(`${app}/generated/proto.d.ts`, "utf8").trimEnd() + "\n" });

// tsc emits every file the entries import at runtime; only the ones their types name belong in the API.
const bodies = new Map<string, string>();
for (const chunk of chunks) if (chunk.space !== undefined) bodies.set(chunk.space, chunk.text);
const kept = new Set<string>();
function reach(text: string): void {
  for (const [ref] of text.matchAll(/(?<![\w$])\$\w+/g)) {
    const body = bodies.get(ref);
    if (body === undefined || kept.has(ref)) continue;
    kept.add(ref);
    reach(body);
  }
}
for (const chunk of chunks) if (chunk.space === undefined) reach(chunk.text);
writeFileSync(posix.join(output, "yuke.d.ts"), chunks.filter((chunk) => chunk.space === undefined || kept.has(chunk.space)).map((chunk) => chunk.text).join("\n"));
writeFileSync(posix.join(output, "yuke-modules.d.ts"), modules.concat("").join("\n"));
