// Bundle the plugin API into one declaration file: the tsc output for the public entries, the hand-written types, and the wire types.
// usage: node tools/typesgen/main.ts <tsc-declaration-dir> <output>
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { posix } from "node:path";

const [emitted, output] = process.argv.slice(2);
if (!emitted || !output) throw new Error("usage: main.ts <tsc-declaration-dir> <output>");
const app = "src/js/app";
// The four entry files are the public modules; every other emitted file is an internal `yuke:` module.
const entry: Record<string, string> = { facade: "yuke", "public-ui": "yuke/ui", "public-chat": "yuke/chat", "public-plugins": "yuke/plugins" };

const list = (dir: string) => readdirSync(dir).filter((name) => name.endsWith(".d.ts")).sort();

// A relative specifier names a sibling file, so it becomes the ambient name of that module.
function rewrite(text: string, base: string): string {
  return text
    .replace(/(from |import\()"(\.{1,2}\/[^"]+)\.js"/g, (_all, lead: string, spec: string) => `${lead}"yuke:${posix.normalize(posix.join(base, spec))}"`)
    .replace(/^export declare /gm, "export ")
    .replace(/^declare /gm, "");
}

const parts = [
  "// GENERATED by tools/typesgen (mise run types). Do not edit.",
  '// The yuke plugin API: "yuke", "yuke/ui", "yuke/chat", and "yuke/plugins".',
  "",
];
for (const name of list(emitted)) {
  const stem = name.slice(0, -".d.ts".length);
  parts.push(`declare module "${entry[stem] ?? "yuke:" + stem}" {`, rewrite(readFileSync(posix.join(emitted, name), "utf8"), ".").trimEnd(), "}", "");
}
for (const name of list(`${app}/types`)) {
  const text = readFileSync(`${app}/types/${name}`, "utf8");
  // A native module is already ambient, and a script declares globals; only a module file needs a wrapper.
  if (!/^(import|export) /m.test(text)) parts.push(text.trimEnd(), "");
  else parts.push(`declare module "yuke:types/${name.slice(0, -".d.ts".length)}" {`, rewrite(text, "types").trimEnd(), "}", "");
}
parts.push(readFileSync(`${app}/generated/proto.d.ts`, "utf8").trimEnd(), "");
writeFileSync(output, parts.join("\n"));
