import { check } from "yuke:test";
import { root } from "yuke:core";
import { Transcript } from "yuke:transcript";
let part = { type: "tool", id: 7, name: "exec", arguments: "{}", state: { type: "completed", duration_ms: 1, output: "old" } };
const copy = (p) => JSON.parse(JSON.stringify(p));
const t = new Transcript({ partsOf: () => [copy(part)], partOf: () => copy(part) });
t.setOutline([], { id: 1, type: "assistant" });
const rows = () => t.rows(80, 0, t.rowCount(80));
const text = () => rows().map((r) => r.text || (r.segments || []).map((s) => s.text).join("")).join("\n");
rows();
const source = t._sourceOf(1);
t.select(t.posAtSource(1, 0), t.posAtSource(1, source.length));
const initial = JSON.stringify(rows());
part.state.output = "fresh hidden output";
t.setActive(1, 7);
check("hidden-rows", JSON.stringify(rows()) === initial);
check("hidden-selection", t.selectedSource() === source);
t.openTool(1, 7);
check("hidden-details", root.overlays[0].content.sections[1].text === part.state.output);
root.popOverlay();
t.togglePart(1, 7);
check("expand-fresh", text().includes("fresh hidden output"));
part.state.output = "visible delta";
t.setActive(1, 7);
check("visible-rows", text().includes("visible delta") && !text().includes("fresh hidden output"));
t.openTool(1, 7);
check("visible-details", root.overlays[0].content.sections[1].text === "visible delta");
root.popOverlay();
t.togglePart(1, 7);
rows();
part.name = "read";
part.arguments = '{"path":"new-path"}';
part.state.duration_ms = 2300;
t.setActive(1, 7);
check("header-fields", text().includes("Read new-path") && text().includes("2.3s"));
part.state = { type: "error", duration_ms: 2400, error: "failed" };
t.setActive(1, 7);
check("error-header", text().includes("error") && text().includes("2.4s"));
part = { type: "reasoning", id: 7, text: "new thought" };
t.setActive(1, 7);
check("same-group-new-kind", text().includes("1 action") && text().includes("thinking") && !text().includes("read"));
