import { check } from "yuke:internal/test";
import { ChatView } from "yuke:internal/chat-view";
import { Session, openSession } from "yuke:internal/chat";
import { client } from "yuke:internal/client";
import { notice } from "yuke:internal/notice";
const opened = [], closed = [];
client.sessionOpen = id => { opened.push(id); return id !== "missing"; };
client.sessionClose = id => { closed.push(id); };
client.sessionActivity = () => null;
client.sessionOutline = () => ({ messages: [{ id: 1, type: "user" }], active: null });
const chat = new ChatView(new Session());
openSession(chat, "missing");
check("failed-first-open", chat.session.sessionId === null && closed.length === 0 && notice.text.includes("open failed"));
openSession(chat, "old");
openSession(chat, "missing");
check("failed-replacement-keeps-pin", chat.session.sessionId === "old" && closed.length === 0 && chat.transcript.messages().length === 1);
openSession(chat, "next");
check("replacement-releases-once", chat.session.sessionId === "next" && closed.join(",") === "old");
openSession(chat, "next");
check("same-session-reuses-pin", opened.join(",") === "missing,old,missing,next");
chat.session.leave(chat);
check("dispose-releases-owned-pin", closed.join(",") === "old,next");
