import { check } from "yuke:test";
import { Chat } from "yuke:chat";
import { client } from "yuke:client";
import { notice } from "yuke:notice";
const opened = [], closed = [];
client.sessionOpen = id => { opened.push(id); return id !== "missing"; };
client.sessionClose = id => { closed.push(id); };
client.sessionActivity = () => null;
client.sessionOutline = () => ({ messages: [{ id: 1, type: "user" }], active: null });
const chat = new Chat();
chat.open("missing");
check("failed-first-open", chat.sessionId === null && closed.length === 0 && notice.text.includes("open failed"));
chat.open("old");
chat.open("missing");
check("failed-replacement-keeps-pin", chat.sessionId === "old" && closed.length === 0 && chat.transcript.messages().length === 1);
chat.open("next");
check("replacement-releases-once", chat.sessionId === "next" && closed.join(",") === "old");
chat.open("next");
check("same-session-reuses-pin", opened.join(",") === "missing,old,missing,next");
chat.dispose();
check("dispose-releases-owned-pin", closed.join(",") === "old,next");
