import { check } from "yuke:internal/test";
import { ChatView } from "yuke:internal/chat-view";
import { command, root, keymap } from "yuke:internal/core";
import { ui } from "yuke:internal/ui";
import { Session, currentChat } from "yuke:internal/chat";
// The shell built the first chat pane at boot.
const chat = currentChat();
const key = (code, o = {}) => ({ type: "key", code, char: "", text: "", event: "press", mods: 0, ...o });
root.focusView(chat);
chat.focus = "composer";
const sent = [];
const msg = (text) => [{ type: "text", text }];
chat.session.startChat = (input) => { sent.push(input.content[0].text); return true; };
let ran = null;
const off = command.add("test:echo", { desc: "d", slash: "echo", args: true, run: (arg) => { ran = arg === undefined ? "" : arg; } });
const rowsOf = () => root.overlays[0].content.list.items;

chat.composer.text = "/";
check("opens", root.overlays.length === 1 && root.overlays[0].modal === false);
check("composer-keeps-focus", root.focused === chat);
check("lists-slash-entries", rowsOf().length > 3 && rowsOf().every((e) => e.slash));
const offAgentsOnly = command.add("test:agents", { desc: "agents", slash: "agents", run: () => {} });
const offModels = command.add("test:models", { desc: "agent models", slash: "agent-models", run: () => {} });
const offAgents = () => { offAgentsOnly(); offModels(); };
chat.composer.text = "/a";
root.overlays[0].content.list.selectKey("test:models");
chat.composer.text = "/agent";
check("new-query-selects-best", root.overlays[0].content.list.selected().slash === "agents");
root.onEvent(key("tab"));
check("agent-completes", chat.composer.text === "/agents");
offAgents();
chat.composer.text = "/ech";
check("filters", rowsOf().length >= 1 && rowsOf()[0].slash === "echo");
root.onEvent(key("tab"));
check("tab-completes-with-space", chat.composer.text === "/echo ");
check("space-closes", root.overlays.length === 0);
chat.composer.text = "/ech";
root.onEvent(key("enter"));
check("enter-runs", ran === "" && chat.composer.text === "");
check("enter-closes", root.overlays.length === 0);
ran = null;
chat.composer.text = "/ech";
root.onEvent(key("esc"));
check("esc-closes", root.overlays.length === 0 && chat.composer.text === "/ech");
chat.composer.text = "/echo";
check("edit-reopens", root.overlays.length === 1);
root.onEvent(key("esc"));
check("send-runs-known", chat.session.send(msg("/echo hello world"), chat.composer) === true && ran === "hello world");
check("send-unknown-is-message", chat.session.send(msg("/foo bar"), chat.composer) === true && sent[sent.length - 1] === "/foo bar");
check("double-slash-is-message", chat.session.send(msg("//x"), chat.composer) === true && sent[sent.length - 1] === "//x");
check("path-is-message", chat.session.send(msg("/tmp/x"), chat.composer) === true && sent[sent.length - 1] === "/tmp/x");
// An attachment makes the line a message, because a command takes the whole input or none of it.
ran = null;
const withImage = [{ type: "text", text: "/echo hello" }, { type: "image", source: { hash: "a".repeat(64), mime: "image/png", bytes: 1 } }];
check("attachment-is-not-a-command", chat.session.send(withImage, chat.composer) === true && ran === null && sent[sent.length - 1] === "/echo hello");
chat.composer.text = "/tmp/x";
check("path-opens-nothing", root.overlays.length === 0);
chat.composer.text = "/zzzz";
check("no-match-opens-nothing", root.overlays.length === 0);
chat.composer.text = "/ech";
chat.focus = "transcript";
chat.focusRegion("composer");
chat.focusRegion("transcript");
check("transcript-focus-closes", root.overlays.length === 0);
chat.focusRegion("composer");
chat.composer.text = "";
// A dialog on top keeps the float shut, so a restored draft never opens a menu under it.
const modal = ui.pick({ items: [] });
root.pushOverlay(modal.win);
chat.composer.text = "/ech";
check("no-float-under-modal", root.overlays.length === 1 && root.overlays[0] === modal.win);
root.popOverlay(modal.win);
chat.composer.text = "";
// Escape dismisses in one pane only, so the same text in another pane still opens its menu.
chat.composer.text = "/ech";
root.onEvent(key("esc"));
const other = new ChatView(new Session());
root.split("row", other);
root.focusView(other);
other.focusRegion("composer");
other.composer.text = "/ech";
check("dismissal-is-per-pane", root.overlays.length === 1);
other.composer.text = "";
root.close();
root.focusView(chat);
chat.focusRegion("composer");
chat.composer.text = "";
// A pending chord takes the next key before the float, so Tab completes nothing here.
chat.composer.text = "/ech";
root.onEvent(key("char", { char: "k", mods: 4 }));
check("chord-armed", keymap.pendingLabel() === "ctrl+k");
root.onEvent(key("tab"));
check("chord-beats-float", chat.composer.text === "/ech" && keymap.pendingLabel() === "");
chat.focusRegion("composer");
chat.composer.text = "";
// A command that left the registry while its row showed runs nothing and keeps the draft.
const gone = command.add("test:gone", { desc: "d", slash: "gone", run: () => {} });
chat.composer.text = "/gone";
check("gone-listed", root.overlays.length === 1);
gone();
root.onEvent(key("enter"));
check("gone-keeps-draft", chat.composer.text === "/gone" && root.overlays.length === 0);
chat.composer.text = "";
off();
