import { root, Node, events } from "yuke:core";
import { plugins } from "yuke:ext";
import { tuiPlugin } from "yuke:tui";
import { Chat } from "yuke:chat";
import { openAgents, childState } from "yuke:agents-ui";
plugins.use(tuiPlugin);
plugins.use({ name: "picker-test", apply(ctx) {
  ctx.inject(["tui"], (ctx) => { (async () => {
    const chat = new Chat();
    root.setRoot(Node.leaf(chat.view)); root.focusView(chat.view);
    const stopped = [];
    client.sessionCancelRun = async (id, clear) => { stopped.push([id, clear]); return {}; };
    client.sessionOpen = () => true;
    client.sessionClose = () => {};
    client.sessionOutline = () => ({ messages: [], active: null });
    chat.sessionId = "01".repeat(16);
    const picker = await openAgents(ctx, chat.sessionId);
    if (!childState(child).includes("completed") || picker.content.source.length !== 2) throw new Error("child row");
    if (!picker.win.opts.title.includes("0 active")) throw new Error("initial summary");
    picker.content.onKey({ type: "key", code: "char", char: "x", mods: 0 });
    if (stopped.length) throw new Error("main stopped");
    child.activity.state = { type: "running_tool", tool_name: "search" };
    events.emit("session.changed", { type: "session", session: child.session.id, facts: ["session.activity_changed"] });
    for (let i = 0; i < 12; i++) await Promise.resolve();
    if (!picker.win.opts.title.includes("1 active") || !childState(child).includes("search")) throw new Error("live summary");
    picker.content.list.move(1);
    picker.content.onKey({ type: "key", code: "char", char: "x", mods: 0 });
    await Promise.resolve(); await Promise.resolve();
    picker.content.onKey({ type: "key", code: "char", char: "X", mods: 0 });
    for (let i = 0; i < 12; i++) await Promise.resolve();
    if (stopped.length !== 2 || stopped.some(([id, clear]) => id !== child.session.id || clear !== true)) throw new Error("stop scope");
    picker.content.onKey({ type: "key", code: "enter", mods: 0 });
    if (chat.sessionId !== child.session.id || root.overlays.length) throw new Error("open child");
    chat.interrupt();
    if (stopped.length !== 3 || stopped[2][0] !== child.session.id || stopped[2][1] !== undefined) throw new Error("interrupt changed scope");
    const back = await openAgents(ctx, chat.sessionId);
    back.content.list.move(-1);
    back.content.accept();
    if (chat.sessionId !== "01".repeat(16)) throw new Error("open main");
    const stale = openAgents(ctx, chat.sessionId);
    chat.sessionId = child.session.id;
    if (await stale || root.overlays.length) throw new Error("stale picker opened");
    chat.dispose();
    result = "ok";
  })().catch((e) => result = e.stack || e.message); });
} });
