import { root, Node } from "yuke:core";
import { events } from "yuke:kernel";
import { plugins, advice } from "yuke:ext";
import { tuiPlugin } from "yuke:tui";
import { Chat } from "yuke:chat";
import { openAgents, childState } from "yuke:agents-ui";
const copy = value => JSON.parse(JSON.stringify(value));
const settle = async () => { for (let i = 0; i < 40; i++) await Promise.resolve(); };
const check = (ok, why) => { if (!ok) throw new Error(why); };
plugins.use(tuiPlugin);
plugins.use({ name: "refresh-test", apply(ctx) {
  ctx.inject(["tui"], ctx => { (async () => {
    const chat = new Chat();
    root.setRoot(Node.leaf(chat.view)); root.focusView(chat.view);
    chat.sessionId = "01".repeat(16);
    let gets = 0, lists = 0, updates = 0, getGate, listGate;
    let children = [child];
    const read = client.sessionGet;
    client.sessionGet = async (...args) => { const value = copy(await read(...args)); if (getGate) await getGate; return value; };
    client.sessionList = async params => {
      const value = { items: params.population.parent_id === chat.sessionId ? copy(children) : [], next_cursor: null, total: children.length };
      if (listGate) await listGate;
      return value;
    };
    const offGet = advice.advise(client, "sessionGet", "before", () => { gets++; });
    const offList = advice.advise(client, "sessionList", "before", () => { lists++; });
    const picker = await openAgents(ctx, chat.sessionId);
    picker.content.list.selectKey(child.session.id);
    const offUpdate = advice.advise(picker.content, "setSource", "after", () => { updates++; });
    const activity = () => events.emit("session.changed", { type: "session", session: child.session.id, kind: "quiet", facts: ["session.activity_changed"] });
    gets = lists = 0;
    child.activity.state = { type: "streaming", run_id: 1, started_at_ms: 1 };
    activity(); await settle();
    check(gets === 1 && lists === 0, "activity must read only the child through advice");
    check(picker.win.opts.title.includes("1 active"), "activity summary");
    check(picker.content.list.selected().item.session.id === child.session.id, "selection moved");
    check(picker.content.source[1].depth === 1 && childState(picker.content.source[1].item) === "working", "row update");
    gets = lists = 0;
    for (let i = 0; i < 20; i++) activity();
    await settle();
    check(gets === 2 && lists === 0, "burst must coalesce pending child reads");
    let release;
    getGate = new Promise(resolve => { release = resolve; });
    activity(); await settle();
    children = [];
    events.emit("session.changed", { type: "session", session: child.session.id, kind: "gone", facts: ["session.removed"] });
    getGate = undefined; release(); await settle();
    check(picker.content.source.length === 1, "late activity restored removed child");
    children = [child];
    events.emit("index.changed", { type: "index", overflow: true, facts: ["catalog.changed"] });
    await settle();
    check(picker.content.source.length === 2, "mixed overflow missed full refresh");
    listGate = new Promise(resolve => { release = resolve; });
    events.emit("index.changed", { type: "index", facts: ["session.summary_changed"] });
    await settle();
    child.activity.state = { type: "idle" }; activity();
    listGate = undefined; release(); await settle();
    check(picker.win.opts.title.includes("0 active"), "activity during full refresh was lost");
    getGate = new Promise(resolve => { release = resolve; });
    activity(); await settle();
    const beforeClose = updates;
    picker.content.cancel();
    getGate = undefined; release(); await settle();
    check(updates === beforeClose && root.overlays.length === 0, "closed picker accepted result");
    offUpdate(); offList(); offGet();
    chat.sessionId = null; chat.dispose();
    result = "ok";
  })().catch(e => result = e.stack || e.message); });
} });
