import { Transcript, inputSourceLabel } from "yuke:transcript";
import { clearWorkQueue, queuedText } from "yuke:queue";
(async () => {
  const source = { type: "child_report", name: "one", outcome: { type: "turn" }, partial: false, truncated: false, usage: { rounds: 1, tool_calls: 0, tokens: { input: 0, output: 0, reasoning: 0, cache_read: 0, cache_write: 0 } } };
  const full = Array.from({ length: 200 }, (_, i) => "line " + i).join("\n");
  const preamble = "Report from one, run 1. Outcome: turn\nThis child report is not user input.\n\n";
  const t = new Transcript({ textOf: () => preamble + full, partsOf: () => [{ type: "text", id: 0, text: preamble }, { type: "text", id: 1, text: full }] });
  t.setOutline([{ id: 1, type: "user", source }], null);
  const rowText = (row) => row.text || (row.segments || []).map((segment) => segment.text).join("");
  const drawn = () => t.rows(80, 0, t.rowCount(80)).map(rowText).join("\n");
  if (drawn().includes("not user input") || !drawn().includes("line 0")) throw new Error("preamble drawn or body missing");
  if (!inputSourceLabel(source).includes("1 round · 0 tools · 0/0 tokens")) throw new Error("usage missing from the header");
  if (t.rowCount(80) > 15 || !inputSourceLabel(source).includes("one")) throw new Error("unfolded report");
  const failed = { ...source, outcome: { type: "failed", code: "provider", message: "the provider returned an unexpected status", detail: "invalid_request_error: too long" } };
  if (!inputSourceLabel(failed).includes("failed · the provider returned an unexpected status · invalid_request_error: too long")) throw new Error("failure missing from the header");
  const child = new Transcript({ textOf: () => "read the file" });
  child.setOutline([{ id: 1, type: "user", source: { type: "parent_instruction", session_id: "01".repeat(16), message_id: 2, part_id: 0 } }], null);
  const childRows = child.rows(80, 0, child.rowCount(80)).map(rowText).join("\n");
  if (!childRows.startsWith("From the parent session") || !childRows.includes("read the file")) throw new Error("parent instruction unlabeled");
  t.togglePart(1, -1);
  if (t.rowCount(80) < 200) throw new Error("lost full report");
  t.togglePart(1, -1);
  if (t.rowCount(80) > 15) throw new Error("cannot fold");
  const report = { input_id: 3, source, content: [{ type: "text", text: full }] };
  const inputs = [{ input_id: 1 }, { input_id: 2, source: { type: "parent_instruction" } }, report];
  client.sessionQueue = async () => ({ items: inputs });
  const canceled = [];
  client.sessionCancelInput = async (_id, inputId) => { canceled.push(inputId); if (inputId === 2) throw new Error("started"); return { canceled_input: inputId }; };
  const result = await clearWorkQueue("parent");
  if (result.removed !== 1 || result.failed !== 1 || result.protected !== 1 || canceled.includes(3)) throw new Error("bad queue count");
  if (!queuedText(report).startsWith("[protected]") || report.content[0].text !== full) throw new Error("report mutation");
  globalThis.result = "ok";
})().catch((e) => result = e.stack || e.message);
