import { textParts } from "yuke:internal/test";
import { Transcript, inputSourceLabel, registerRender } from "yuke:internal/transcript";
import { defaultRender } from "yuke:internal/transcript-view";
import { clearWorkQueue, queuedText } from "yuke:internal/queue";

registerRender(defaultRender);
(async () => {
  const source = { type: "child_report", name: "one", outcome: { type: "turn" }, usage: { rounds: 1, tool_calls: 0, tokens: { input: 0, output: 0, reasoning: 0, cache_read: 0, cache_write: 0 }, duration_ms: 1500 } };
  const full = Array.from({ length: 200 }, (_, i) => "line " + i).join("\n");
  const preamble = "[one-a91c07d2 completed. This message is not from the user.]\n";
  const t = new Transcript({ partsOf: () => [{ type: "text", id: 0, text: preamble }, { type: "text", id: 1, text: full }] });
  t.setOutline([{ id: 1, type: "user", source }], null);
  const rowText = (row) => row.text || (row.segments || []).map((segment) => segment.text).join("");
  const drawn = () => t.rows(80, 0, t.rowCount(80)).map(rowText).join("\n");
  if (drawn().includes("not from the user") || !drawn().includes("line 0")) throw new Error("header drawn or body missing");
  // A job end draws its body alone too.
  const job = new Transcript({ partsOf: () => [{ type: "text", id: 0, text: "[job-k3x9 exited 1. This message is not from the user.]\n" }, { type: "text", id: 1, text: "Log: /tmp/l\nboom" }] });
  job.setOutline([{ id: 1, type: "user", source: { type: "job_ended", job_id: 50000, command: "make", exit_code: 1 } }], null);
  const jobText = job.rows(80, 0, job.rowCount(80)).map(rowText).join("\n");
  if (jobText.includes("not from the user") || !jobText.includes("boom")) throw new Error("job end header drawn or body missing: " + jobText);
  if (!inputSourceLabel(source).includes("1 round · 0 tools · 0/0 tokens · 1.5s")) throw new Error("usage missing from the header");
  if (t.rowCount(80) > 15 || !inputSourceLabel(source).includes("one")) throw new Error("unfolded report");
  const failed = { ...source, outcome: { type: "failed", code: "provider", message: "the provider returned an unexpected status", detail: "invalid_request_error: too long" } };
  if (!inputSourceLabel(failed).includes("failed · the provider returned an unexpected status · invalid_request_error: too long")) throw new Error("failure missing from the header");
  const child = new Transcript({ partsOf: textParts(() => "read the file") });
  child.setOutline([{ id: 1, type: "user", source: { type: "parent_instruction", session_id: "01".repeat(16), message_id: 2, part_id: 0 } }], null);
  const childRows = child.rows(80, 0, child.rowCount(80)).map(rowText).join("\n");
  if (!childRows.startsWith("From the parent session") || !childRows.includes("read the file")) throw new Error("parent instruction unlabeled");
  t.togglePart(1, -1);
  if (t.rowCount(80) < 200) throw new Error("lost full report");
  t.togglePart(1, -1);
  if (t.rowCount(80) > 15) throw new Error("cannot fold");
  const report = { input_id: 3, source, content: [{ type: "text", text: full }] };
  const inputs = [{ input_id: 1 }, { input_id: 2, source: { type: "parent_instruction" } }, report];
  client.sessionQueue = async () => ({ items: inputs });
  const canceled = [];
  client.sessionCancelInput = async (_id, inputId) => { canceled.push(inputId); if (inputId === 2) throw new Error("started"); return { canceled_input: inputId }; };
  const result = await clearWorkQueue("parent");
  if (result.removed !== 1 || result.failed !== 1 || result.protected !== 1 || canceled.includes(3)) throw new Error("bad queue count");
  if (!queuedText(report).startsWith("[protected]") || report.content[0].text !== full) throw new Error("report mutation");
  globalThis.result = "ok";
})().catch((e) => result = e.stack || e.message);
